import Blocks from "./blocks.js";

export default class LevelInit1 {
  LevelSetup1(Levels) {
    Levels.push([
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Block"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(4, 4, "Block"),
      new Blocks(5, 4, "Block"),
      new Blocks(6, 4, "Block"),
      new Blocks(12, 4, "Block"),
      new Blocks(13, 4, "Block"),
      new Blocks(14, 4, "Block"),
      new Blocks(20, 4, "Block"),
      new Blocks(21, 4, "Block"),
      new Blocks(22, 4, "Block"),
      new Blocks(0, 7, "Block"),
      new Blocks(1, 7, "Block"),
      new Blocks(2, 7, "Block"),
      new Blocks(4, 10, "Block"),
      new Blocks(5, 10, "Block"),
      new Blocks(6, 10, "Block"),
      new Blocks(8, 13, "Block"),
      new Blocks(9, 13, "Block"),
      new Blocks(10, 13, "Block"),
      new Blocks(4, 16, "Block"),
      new Blocks(5, 16, "Block"),
      new Blocks(6, 16, "Block"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(5, 3, "Speed", "Up"),
      new Blocks(26, 3, "Block"),
      new Blocks(1, 4, "Speed", "Up"),
      new Blocks(18, 4, "Speed", "Up"),
      new Blocks(26, 4, "Block"),
      new Blocks(11, 5, "Speed", "Up"),
      new Blocks(22, 5, "Speed", "Up"),
      new Blocks(26, 5, "Block"),
      new Blocks(26, 6, "Block"),
      new Blocks(4, 7, "Speed", "Up"),
      new Blocks(10, 7, "Speed", "Up"),
      new Blocks(26, 7, "Block"),
      new Blocks(7, 8, "Speed", "Up"),
      new Blocks(16, 8, "Speed", "Up"),
      new Blocks(20, 8, "Speed", "Up"),
      new Blocks(26, 8, "Block"),
      new Blocks(26, 9, "Block"),
      new Blocks(1, 10, "Speed", "Up"),
      new Blocks(6, 10, "Speed", "Up"),
      new Blocks(24, 10, "Speed", "Up"),
      new Blocks(26, 10, "Block"),
      new Blocks(12, 11, "Speed", "Up"),
      new Blocks(26, 11, "Block"),
      new Blocks(26, 12, "Block"),
      new Blocks(15, 13, "Speed", "Up"),
      new Blocks(26, 13, "Block"),
      new Blocks(3, 14, "Speed", "Up"),
      new Blocks(9, 14, "Speed", "Up"),
      new Blocks(21, 14, "Speed", "Up"),
      new Blocks(26, 14, "Block"),
      new Blocks(18, 15, "Speed", "Up"),
      new Blocks(26, 15, "Block"),
      new Blocks(5, 16, "Speed", "Up"),
      new Blocks(12, 16, "Speed", "Up"),
      new Blocks(24, 16, "Speed", "Up"),
      new Blocks(26, 16, "Block"),
      new Blocks(26, 17, "Block"),
      new Blocks(26, 18, "Block"),
      new Blocks(0, 19, "Speed", "Up"),
      new Blocks(1, 19, "Speed", "Up"),
      new Blocks(2, 19, "Speed", "Up"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(19, 2, "Red"),
      new Blocks(20, 2, "Red"),
      new Blocks(21, 2, "Red"),
      new Blocks(11, 3, "Blue"),
      new Blocks(12, 3, "Blue"),
      new Blocks(13, 3, "Blue"),
      new Blocks(25, 3, "Blue"),
      new Blocks(26, 3, "Red"),
      new Blocks(3, 4, "Red"),
      new Blocks(4, 4, "Red"),
      new Blocks(5, 4, "Red"),
      new Blocks(25, 4, "Blue"),
      new Blocks(26, 4, "Red"),
      new Blocks(25, 5, "Blue"),
      new Blocks(26, 5, "Red"),
      new Blocks(25, 6, "Blue"),
      new Blocks(26, 6, "Red"),
      new Blocks(11, 7, "Blue"),
      new Blocks(12, 7, "Blue"),
      new Blocks(13, 7, "Blue"),
      new Blocks(25, 7, "Blue"),
      new Blocks(26, 7, "Red"),
      new Blocks(25, 8, "Blue"),
      new Blocks(26, 8, "Red"),
      new Blocks(25, 9, "Blue"),
      new Blocks(26, 9, "Red"),
      new Blocks(19, 10, "Red"),
      new Blocks(20, 10, "Red"),
      new Blocks(21, 10, "Red"),
      new Blocks(25, 10, "Blue"),
      new Blocks(26, 10, "Red"),
      new Blocks(25, 11, "Blue"),
      new Blocks(26, 11, "Red"),
      new Blocks(25, 12, "Blue"),
      new Blocks(26, 12, "Red"),
      new Blocks(11, 13, "Blue"),
      new Blocks(12, 13, "Blue"),
      new Blocks(13, 13, "Blue"),
      new Blocks(25, 13, "Blue"),
      new Blocks(26, 13, "Red"),
      new Blocks(25, 14, "Blue"),
      new Blocks(26, 14, "Red"),
      new Blocks(25, 15, "Blue"),
      new Blocks(26, 15, "Red"),
      new Blocks(3, 16, "Red"),
      new Blocks(4, 16, "Red"),
      new Blocks(5, 16, "Red"),
      new Blocks(25, 16, "Blue"),
      new Blocks(26, 16, "Red"),
      new Blocks(25, 17, "Blue"),
      new Blocks(26, 17, "Red"),
      new Blocks(25, 18, "Blue"),
      new Blocks(26, 18, "Red"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Block"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(5, 0, "Block"),
      new Blocks(8, 0, "Portal", "", "Portal", 10, 13),
      new Blocks(11, 0, "Block"),
      new Blocks(18, 0, "Block"),
      new Blocks(21, 0, "Portal", "", "Portal", 23, 13),
      new Blocks(24, 0, "Block"),
      new Blocks(5, 1, "Block"),
      new Blocks(7, 1, "Platform"),
      new Blocks(8, 1, "Platform"),
      new Blocks(9, 1, "Platform"),
      new Blocks(11, 1, "Block"),
      new Blocks(18, 1, "Block"),
      new Blocks(20, 1, "Platform"),
      new Blocks(21, 1, "Platform"),
      new Blocks(22, 1, "Platform"),
      new Blocks(24, 1, "Block"),
      new Blocks(27, 1, "Key", "", "Key"),
      new Blocks(5, 2, "Block"),
      new Blocks(11, 2, "Block"),
      new Blocks(18, 2, "Block"),
      new Blocks(24, 2, "Block"),
      new Blocks(2, 3, "Portal", "", "Portal", 10, 8),
      new Blocks(5, 3, "Block"),
      new Blocks(6, 3, "Portal", "", "Portal", 12, 13),
      new Blocks(10, 3, "Portal", "", "Portal", 2, 13),
      new Blocks(11, 3, "Block"),
      new Blocks(12, 3, "Portal", "", "Portal", 23, 3),
      new Blocks(17, 3, "Portal", "", "Portal", 2, 8),
      new Blocks(18, 3, "Block"),
      new Blocks(19, 3, "Portal", "", "Portal", 12, 18),
      new Blocks(23, 3, "Portal", "", "Portal", 12, 3),
      new Blocks(24, 3, "Block"),
      new Blocks(27, 3, "Portal", "", "Portal", 17, 8),
      new Blocks(0, 4, "Block"),
      new Blocks(1, 4, "Block"),
      new Blocks(2, 4, "Block"),
      new Blocks(3, 4, "Block"),
      new Blocks(4, 4, "Block"),
      new Blocks(5, 4, "Block"),
      new Blocks(6, 4, "Block"),
      new Blocks(7, 4, "Block"),
      new Blocks(8, 4, "Block"),
      new Blocks(9, 4, "Block"),
      new Blocks(10, 4, "Block"),
      new Blocks(11, 4, "Block"),
      new Blocks(12, 4, "Block"),
      new Blocks(13, 4, "Block"),
      new Blocks(14, 4, "Block"),
      new Blocks(15, 4, "Block"),
      new Blocks(16, 4, "Block"),
      new Blocks(17, 4, "Block"),
      new Blocks(18, 4, "Block"),
      new Blocks(19, 4, "Block"),
      new Blocks(20, 4, "Block"),
      new Blocks(21, 4, "Block"),
      new Blocks(22, 4, "Block"),
      new Blocks(23, 4, "Block"),
      new Blocks(24, 4, "Block"),
      new Blocks(25, 4, "Block"),
      new Blocks(26, 4, "Block"),
      new Blocks(27, 4, "Block"),
      new Blocks(28, 4, "Block"),
      new Blocks(29, 4, "Block"),
      new Blocks(5, 5, "Block"),
      new Blocks(8, 5, "Portal", "", "Portal", 6, 13),
      new Blocks(11, 5, "Block"),
      new Blocks(18, 5, "Block"),
      new Blocks(21, 5, "Portal", "", "Portal", 19, 13),
      new Blocks(24, 5, "Block"),
      new Blocks(5, 6, "Block"),
      new Blocks(7, 6, "Platform"),
      new Blocks(8, 6, "Platform"),
      new Blocks(9, 6, "Platform"),
      new Blocks(11, 6, "Block"),
      new Blocks(18, 6, "Block"),
      new Blocks(20, 6, "Platform"),
      new Blocks(21, 6, "Platform"),
      new Blocks(22, 6, "Platform"),
      new Blocks(24, 6, "Block"),
      new Blocks(5, 7, "Block"),
      new Blocks(11, 7, "Block"),
      new Blocks(18, 7, "Block"),
      new Blocks(24, 7, "Block"),
      new Blocks(2, 8, "Portal", "", "Portal", 17, 3),
      new Blocks(5, 8, "Block"),
      new Blocks(6, 8, "Portal", "", "Portal", 12, 8),
      new Blocks(10, 8, "Portal", "", "Portal", 2, 3),
      new Blocks(11, 8, "Block"),
      new Blocks(12, 8, "Portal", "", "Portal", 6, 8),
      new Blocks(17, 8, "Portal", "", "Portal", 27, 3),
      new Blocks(18, 8, "Block"),
      new Blocks(19, 8, "Portal", "", "Portal", 27, 8),
      new Blocks(23, 8, "Portal", "", "Portal", 21, 15),
      new Blocks(24, 8, "Block"),
      new Blocks(27, 8, "Portal", "", "Portal", 19, 8),
      new Blocks(0, 9, "Block"),
      new Blocks(1, 9, "Block"),
      new Blocks(2, 9, "Block"),
      new Blocks(3, 9, "Block"),
      new Blocks(4, 9, "Block"),
      new Blocks(5, 9, "Block"),
      new Blocks(6, 9, "Block"),
      new Blocks(7, 9, "Block"),
      new Blocks(8, 9, "Block"),
      new Blocks(9, 9, "Block"),
      new Blocks(10, 9, "Block"),
      new Blocks(11, 9, "Block"),
      new Blocks(12, 9, "Block"),
      new Blocks(13, 9, "Block"),
      new Blocks(14, 9, "Block"),
      new Blocks(15, 9, "Block"),
      new Blocks(16, 9, "Block"),
      new Blocks(17, 9, "Block"),
      new Blocks(18, 9, "Block"),
      new Blocks(19, 9, "Block"),
      new Blocks(20, 9, "Block"),
      new Blocks(21, 9, "Block"),
      new Blocks(22, 9, "Block"),
      new Blocks(23, 9, "Block"),
      new Blocks(24, 9, "Block"),
      new Blocks(25, 9, "Block"),
      new Blocks(26, 9, "Block"),
      new Blocks(27, 9, "Block"),
      new Blocks(28, 9, "Block"),
      new Blocks(29, 9, "Block"),
      new Blocks(5, 10, "Block"),
      new Blocks(8, 10, "Portal", "", "Portal", 6, 18),
      new Blocks(11, 10, "Block"),
      new Blocks(18, 10, "Block"),
      new Blocks(21, 10, "Portal", "", "Portal", 10, 18),
      new Blocks(24, 10, "Block"),
      new Blocks(5, 11, "Block"),
      new Blocks(7, 11, "Platform"),
      new Blocks(8, 11, "Platform"),
      new Blocks(9, 11, "Platform"),
      new Blocks(11, 11, "Block"),
      new Blocks(18, 11, "Block"),
      new Blocks(20, 11, "Platform"),
      new Blocks(21, 11, "Platform"),
      new Blocks(22, 11, "Platform"),
      new Blocks(24, 11, "Block"),
      new Blocks(5, 12, "Block"),
      new Blocks(11, 12, "Block"),
      new Blocks(18, 12, "Block"),
      new Blocks(24, 12, "Block"),
      new Blocks(2, 13, "Portal", "", "Portal", 10, 3),
      new Blocks(5, 13, "Block"),
      new Blocks(6, 13, "Portal", "", "Portal", 8, 5),
      new Blocks(10, 13, "Portal", "", "Portal", 8, 0),
      new Blocks(11, 13, "Block"),
      new Blocks(12, 13, "Portal", "", "Portal", 6, 3),
      new Blocks(17, 13, "Portal", "", "Portal", 27, 13),
      new Blocks(18, 13, "Block"),
      new Blocks(19, 13, "Portal", "", "Portal", 21, 5),
      new Blocks(23, 13, "Portal", "", "Portal", 21, 0),
      new Blocks(24, 13, "Block"),
      new Blocks(27, 13, "Portal", "", "Portal", 17, 13),
      new Blocks(0, 14, "Block"),
      new Blocks(1, 14, "Block"),
      new Blocks(2, 14, "Block"),
      new Blocks(3, 14, "Block"),
      new Blocks(4, 14, "Block"),
      new Blocks(5, 14, "Block"),
      new Blocks(6, 14, "Block"),
      new Blocks(7, 14, "Block"),
      new Blocks(8, 14, "Block"),
      new Blocks(9, 14, "Block"),
      new Blocks(10, 14, "Block"),
      new Blocks(11, 14, "Block"),
      new Blocks(12, 14, "Block"),
      new Blocks(13, 14, "Block"),
      new Blocks(14, 14, "Block"),
      new Blocks(15, 14, "Block"),
      new Blocks(16, 14, "Block"),
      new Blocks(17, 14, "Block"),
      new Blocks(18, 14, "Block"),
      new Blocks(19, 14, "Block"),
      new Blocks(20, 14, "Block"),
      new Blocks(21, 14, "Block"),
      new Blocks(22, 14, "Block"),
      new Blocks(23, 14, "Block"),
      new Blocks(24, 14, "Block"),
      new Blocks(25, 14, "Block"),
      new Blocks(26, 14, "Block"),
      new Blocks(27, 14, "Block"),
      new Blocks(28, 14, "Block"),
      new Blocks(29, 14, "Block"),
      new Blocks(5, 15, "Block"),
      new Blocks(8, 15, "Portal", "", "Portal", 3, 18),
      new Blocks(11, 15, "Block"),
      new Blocks(18, 15, "Block"),
      new Blocks(21, 15, "Portal", "", "Portal", 23, 8),
      new Blocks(24, 15, "Block"),
      new Blocks(5, 16, "Block"),
      new Blocks(7, 16, "Platform"),
      new Blocks(8, 16, "Platform"),
      new Blocks(9, 16, "Platform"),
      new Blocks(11, 16, "Block"),
      new Blocks(18, 16, "Block"),
      new Blocks(20, 16, "Platform"),
      new Blocks(21, 16, "Platform"),
      new Blocks(22, 16, "Platform"),
      new Blocks(24, 16, "Block"),
      new Blocks(5, 17, "Block"),
      new Blocks(11, 17, "Block"),
      new Blocks(18, 17, "Block"),
      new Blocks(24, 17, "Block"),
      new Blocks(3, 18, "Portal", "", "Portal", 8, 15),
      new Blocks(5, 18, "Block"),
      new Blocks(6, 18, "Portal", "", "Portal", 8, 10),
      new Blocks(10, 18, "Portal", "", "Portal", 21, 10),
      new Blocks(11, 18, "Block"),
      new Blocks(12, 18, "Portal", "", "Portal", 19, 3),
      new Blocks(17, 18, "LockedPortal", "", "LockedPortal", 26, 18),
      new Blocks(18, 18, "Block"),
      new Blocks(19, 18, "Portal", "", "Portal", 23, 18),
      new Blocks(23, 18, "Portal", "", "Portal", 19, 18),
      new Blocks(24, 18, "Block"),
      new Blocks(26, 18, "LockedPortal", "", "LockedPortal", 17, 18),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Block"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(23, 0, "Lava"),
      new Blocks(23, 1, "Lava"),
      new Blocks(23, 2, "Lava"),
      new Blocks(26, 2, "Lava"),
      new Blocks(23, 3, "Lava"),
      new Blocks(26, 3, "Lava"),
      new Blocks(23, 4, "Lava"),
      new Blocks(24, 4, "Platform"),
      new Blocks(25, 4, "Lava"),
      new Blocks(26, 4, "Lava"),
      new Blocks(26, 5, "Block"),
      new Blocks(26, 6, "Block"),
      new Blocks(0, 7, "Platform"),
      new Blocks(1, 7, "Platform"),
      new Blocks(2, 7, "Block"),
      new Blocks(3, 7, "Lava"),
      new Blocks(4, 7, "Lava"),
      new Blocks(5, 7, "Lava"),
      new Blocks(6, 7, "Lava"),
      new Blocks(7, 7, "Lava"),
      new Blocks(8, 7, "Lava"),
      new Blocks(9, 7, "Lava"),
      new Blocks(10, 7, "Lava"),
      new Blocks(11, 7, "Lava"),
      new Blocks(12, 7, "Block"),
      new Blocks(13, 7, "Block"),
      new Blocks(14, 7, "Lava"),
      new Blocks(15, 7, "Lava"),
      new Blocks(16, 7, "Lava"),
      new Blocks(17, 7, "Lava"),
      new Blocks(18, 7, "Lava"),
      new Blocks(19, 7, "Lava"),
      new Blocks(20, 7, "Lava"),
      new Blocks(21, 7, "Lava"),
      new Blocks(22, 7, "Lava"),
      new Blocks(23, 7, "Block"),
      new Blocks(24, 7, "Block"),
      new Blocks(25, 7, "Block"),
      new Blocks(26, 7, "Block"),
      new Blocks(2, 8, "Block"),
      new Blocks(3, 8, "Block"),
      new Blocks(4, 8, "Block"),
      new Blocks(5, 8, "Block"),
      new Blocks(6, 8, "Block"),
      new Blocks(7, 8, "Block"),
      new Blocks(8, 8, "Block"),
      new Blocks(9, 8, "Block"),
      new Blocks(10, 8, "Block"),
      new Blocks(11, 8, "Block"),
      new Blocks(12, 8, "Block"),
      new Blocks(13, 8, "Block"),
      new Blocks(14, 8, "Block"),
      new Blocks(15, 8, "Block"),
      new Blocks(16, 8, "Block"),
      new Blocks(17, 8, "Block"),
      new Blocks(18, 8, "Block"),
      new Blocks(19, 8, "Block"),
      new Blocks(20, 8, "Block"),
      new Blocks(21, 8, "Block"),
      new Blocks(22, 8, "Block"),
      new Blocks(23, 8, "Block"),
      new Blocks(24, 8, "Block"),
      new Blocks(25, 8, "Block"),
      new Blocks(26, 8, "Block"),
      new Blocks(26, 9, "Block"),
      new Blocks(0, 10, "Platform"),
      new Blocks(1, 10, "Platform"),
      new Blocks(26, 10, "Block"),
      new Blocks(26, 11, "Block"),
      new Blocks(26, 12, "Block"),
      new Blocks(0, 13, "Block"),
      new Blocks(1, 13, "Block"),
      new Blocks(2, 13, "Lava"),
      new Blocks(3, 13, "Lava"),
      new Blocks(4, 13, "Lava"),
      new Blocks(5, 13, "Lava"),
      new Blocks(6, 13, "Lava"),
      new Blocks(7, 13, "Lava"),
      new Blocks(8, 13, "Lava"),
      new Blocks(9, 13, "Lava"),
      new Blocks(10, 13, "Lava"),
      new Blocks(11, 13, "Block"),
      new Blocks(12, 13, "Block"),
      new Blocks(13, 13, "Lava"),
      new Blocks(14, 13, "Lava"),
      new Blocks(15, 13, "Lava"),
      new Blocks(16, 13, "Lava"),
      new Blocks(17, 13, "Lava"),
      new Blocks(18, 13, "Lava"),
      new Blocks(19, 13, "Lava"),
      new Blocks(20, 13, "Lava"),
      new Blocks(21, 13, "Lava"),
      new Blocks(22, 13, "Block"),
      new Blocks(23, 13, "Platform"),
      new Blocks(24, 13, "Platform"),
      new Blocks(25, 13, "Platform"),
      new Blocks(26, 13, "Block"),
      new Blocks(0, 14, "Block"),
      new Blocks(1, 14, "Block"),
      new Blocks(2, 14, "Block"),
      new Blocks(3, 14, "Block"),
      new Blocks(4, 14, "Block"),
      new Blocks(5, 14, "Block"),
      new Blocks(6, 14, "Block"),
      new Blocks(7, 14, "Block"),
      new Blocks(8, 14, "Block"),
      new Blocks(9, 14, "Block"),
      new Blocks(10, 14, "Block"),
      new Blocks(11, 14, "Block"),
      new Blocks(12, 14, "Block"),
      new Blocks(13, 14, "Block"),
      new Blocks(14, 14, "Block"),
      new Blocks(15, 14, "Block"),
      new Blocks(16, 14, "Block"),
      new Blocks(17, 14, "Block"),
      new Blocks(18, 14, "Block"),
      new Blocks(19, 14, "Block"),
      new Blocks(20, 14, "Block"),
      new Blocks(21, 14, "Block"),
      new Blocks(22, 14, "Block"),
      new Blocks(26, 14, "Block"),
      new Blocks(26, 15, "Block"),
      new Blocks(24, 16, "Platform"),
      new Blocks(25, 16, "Platform"),
      new Blocks(26, 16, "Block"),
      new Blocks(3, 17, "Lava"),
      new Blocks(6, 17, "Lava"),
      new Blocks(9, 17, "Lava"),
      new Blocks(12, 17, "Lava"),
      new Blocks(15, 17, "Lava"),
      new Blocks(18, 17, "Lava"),
      new Blocks(21, 17, "Lava"),
      new Blocks(26, 17, "Block"),
      new Blocks(3, 18, "Lava"),
      new Blocks(6, 18, "Lava"),
      new Blocks(9, 18, "Lava"),
      new Blocks(12, 18, "Lava"),
      new Blocks(15, 18, "Lava"),
      new Blocks(18, 18, "Lava"),
      new Blocks(21, 18, "Lava"),
      new Blocks(26, 18, "Block"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Block"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(26, 0, "Lava"),
      new Blocks(27, 0, "Lava"),
      new Blocks(28, 0, "Lava"),
      new Blocks(29, 0, "Lava"),
      new Blocks(26, 1, "Lava"),
      new Blocks(27, 1, "Lava"),
      new Blocks(28, 1, "Portal", "", "Portal", 20, 17),
      new Blocks(29, 1, "Lava"),
      new Blocks(26, 2, "Lava"),
      new Blocks(27, 2, "Lava"),
      new Blocks(29, 2, "Lava"),
      new Blocks(26, 3, "Lava"),
      new Blocks(27, 3, "Lava"),
      new Blocks(29, 3, "Lava"),
      new Blocks(26, 4, "Lava"),
      new Blocks(7, 5, "Portal", "", "Portal", 1, 17),
      new Blocks(14, 5, "Lava"),
      new Blocks(15, 5, "Lava"),
      new Blocks(26, 5, "Lava"),
      new Blocks(14, 6, "Lava"),
      new Blocks(15, 6, "Lava"),
      new Blocks(26, 6, "Lava"),
      new Blocks(14, 7, "Lava"),
      new Blocks(15, 7, "Lava"),
      new Blocks(26, 7, "Lava"),
      new Blocks(14, 8, "Lava"),
      new Blocks(15, 8, "Lava"),
      new Blocks(26, 8, "Lava"),
      new Blocks(0, 9, "Lava"),
      new Blocks(1, 9, "Lava"),
      new Blocks(2, 9, "Lava"),
      new Blocks(3, 9, "Lava"),
      new Blocks(4, 9, "Lava"),
      new Blocks(5, 9, "Lava"),
      new Blocks(6, 9, "Lava"),
      new Blocks(7, 9, "Lava"),
      new Blocks(8, 9, "Lava"),
      new Blocks(9, 9, "Lava"),
      new Blocks(10, 9, "Lava"),
      new Blocks(11, 9, "Lava"),
      new Blocks(12, 9, "Lava"),
      new Blocks(13, 9, "Lava"),
      new Blocks(14, 9, "Lava"),
      new Blocks(15, 9, "Lava"),
      new Blocks(26, 9, "Lava"),
      new Blocks(14, 10, "Lava"),
      new Blocks(15, 10, "Lava"),
      new Blocks(26, 10, "Lava"),
      new Blocks(14, 11, "Lava"),
      new Blocks(15, 11, "Lava"),
      new Blocks(26, 11, "Lava"),
      new Blocks(14, 12, "Lava"),
      new Blocks(15, 12, "Lava"),
      new Blocks(26, 12, "Lava"),
      new Blocks(14, 13, "Lava"),
      new Blocks(15, 13, "Lava"),
      new Blocks(26, 13, "Lava"),
      new Blocks(14, 14, "Lava"),
      new Blocks(15, 14, "Lava"),
      new Blocks(26, 14, "Lava"),
      new Blocks(14, 15, "Lava"),
      new Blocks(15, 15, "Lava"),
      new Blocks(26, 15, "Lava"),
      new Blocks(14, 16, "Lava"),
      new Blocks(15, 16, "Lava"),
      new Blocks(26, 16, "Lava"),
      new Blocks(1, 17, "Portal", "", "Portal", 7, 5),
      new Blocks(14, 17, "Lava"),
      new Blocks(15, 17, "Lava"),
      new Blocks(20, 17, "Portal", "", "Portal", 28, 1),
      new Blocks(26, 17, "Lava"),
      new Blocks(14, 18, "Lava"),
      new Blocks(15, 18, "Lava"),
      new Blocks(26, 18, "Lava"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(14, 19, "Lava"),
      new Blocks(15, 19, "Lava"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(0, 0, "Key", "", "Key"),
      new Blocks(24, 0, "LockedPortal", "", "LockedPortal", 24, 3),
      new Blocks(26, 0, "Lava"),
      new Blocks(0, 1, "Blue"),
      new Blocks(22, 1, "Block"),
      new Blocks(23, 1, "Platform"),
      new Blocks(24, 1, "Platform"),
      new Blocks(25, 1, "Platform"),
      new Blocks(26, 1, "Lava"),
      new Blocks(22, 2, "Lava"),
      new Blocks(26, 2, "Lava"),
      new Blocks(22, 3, "Lava"),
      new Blocks(24, 3, "LockedPortal", "", "LockedPortal", 24, 0),
      new Blocks(26, 3, "Lava"),
      new Blocks(0, 4, "Red"),
      new Blocks(19, 4, "Red"),
      new Blocks(20, 4, "Red"),
      new Blocks(21, 4, "Red"),
      new Blocks(22, 4, "Lava"),
      new Blocks(23, 4, "Red"),
      new Blocks(24, 4, "Red"),
      new Blocks(25, 4, "Red"),
      new Blocks(26, 4, "Lava"),
      new Blocks(22, 5, "Lava"),
      new Blocks(26, 5, "Lava"),
      new Blocks(22, 6, "Lava"),
      new Blocks(26, 6, "Lava"),
      new Blocks(0, 7, "Blue"),
      new Blocks(15, 7, "Blue"),
      new Blocks(16, 7, "Blue"),
      new Blocks(17, 7, "Blue"),
      new Blocks(22, 7, "Lava"),
      new Blocks(26, 7, "Lava"),
      new Blocks(22, 8, "Lava"),
      new Blocks(26, 8, "Lava"),
      new Blocks(22, 9, "Lava"),
      new Blocks(26, 9, "Lava"),
      new Blocks(0, 10, "Red"),
      new Blocks(11, 10, "Red"),
      new Blocks(12, 10, "Red"),
      new Blocks(13, 10, "Red"),
      new Blocks(22, 10, "Lava"),
      new Blocks(26, 10, "Lava"),
      new Blocks(22, 11, "Lava"),
      new Blocks(26, 11, "Lava"),
      new Blocks(22, 12, "Lava"),
      new Blocks(26, 12, "Lava"),
      new Blocks(0, 13, "Blue"),
      new Blocks(7, 13, "Blue"),
      new Blocks(8, 13, "Blue"),
      new Blocks(9, 13, "Blue"),
      new Blocks(22, 13, "Lava"),
      new Blocks(26, 13, "Lava"),
      new Blocks(22, 14, "Lava"),
      new Blocks(26, 14, "Lava"),
      new Blocks(22, 15, "Lava"),
      new Blocks(26, 15, "Red"),
      new Blocks(0, 16, "Red"),
      new Blocks(3, 16, "Red"),
      new Blocks(4, 16, "Red"),
      new Blocks(5, 16, "Red"),
      new Blocks(22, 16, "Lava"),
      new Blocks(26, 16, "Red"),
      new Blocks(22, 17, "Lava"),
      new Blocks(26, 17, "Red"),
      new Blocks(22, 18, "Lava"),
      new Blocks(26, 18, "Red"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(22, 19, "Lava"),
      new Blocks(23, 19, "Red"),
      new Blocks(24, 19, "Red"),
      new Blocks(25, 19, "Red"),
      new Blocks(26, 19, "Red"),
      new Blocks(27, 19, "Red"),
      new Blocks(28, 19, "Red"),
      new Blocks(29, 19, "Red"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(14, 0, "Block"),
      new Blocks(16, 0, "Block"),
      new Blocks(14, 1, "Block"),
      new Blocks(16, 1, "Block"),
      new Blocks(14, 2, "Block"),
      new Blocks(16, 2, "Block"),
      new Blocks(14, 3, "Block"),
      new Blocks(16, 3, "Block"),
      new Blocks(14, 4, "Block"),
      new Blocks(16, 4, "Block"),
      new Blocks(14, 5, "Block"),
      new Blocks(16, 5, "Block"),
      new Blocks(0, 6, "Block"),
      new Blocks(1, 6, "Block"),
      new Blocks(2, 6, "Block"),
      new Blocks(3, 6, "Block"),
      new Blocks(4, 6, "Block"),
      new Blocks(5, 6, "Block"),
      new Blocks(14, 6, "Block"),
      new Blocks(15, 6, "Key", "", "Key"),
      new Blocks(16, 6, "Block"),
      new Blocks(5, 7, "Block"),
      new Blocks(14, 7, "Block"),
      new Blocks(15, 7, "Portal", "", "Portal", 28, 9),
      new Blocks(16, 7, "Block"),
      new Blocks(24, 7, "Block"),
      new Blocks(25, 7, "Block"),
      new Blocks(26, 7, "Block"),
      new Blocks(27, 7, "Block"),
      new Blocks(28, 7, "Block"),
      new Blocks(29, 7, "Block"),
      new Blocks(2, 8, "Key", "", "Key"),
      new Blocks(5, 8, "Block"),
      new Blocks(14, 8, "Block"),
      new Blocks(16, 8, "Block"),
      new Blocks(24, 8, "Block"),
      new Blocks(29, 8, "Block"),
      new Blocks(5, 9, "Block"),
      new Blocks(14, 9, "Block"),
      new Blocks(16, 9, "Block"),
      new Blocks(24, 9, "Block"),
      new Blocks(28, 9, "Portal", "", "Portal", 15, 7),
      new Blocks(29, 9, "Block"),
      new Blocks(2, 10, "Portal", "", "Portal", 3, 18),
      new Blocks(5, 10, "Block"),
      new Blocks(14, 10, "Block"),
      new Blocks(15, 10, "LockedPortal", "", "LockedPortal", 28, 12),
      new Blocks(16, 10, "Block"),
      new Blocks(24, 10, "Block"),
      new Blocks(25, 10, "LockedPortal", "", "LockedPortal", 0, 18),
      new Blocks(27, 10, "Lava"),
      new Blocks(29, 10, "Block"),
      new Blocks(5, 11, "Block"),
      new Blocks(14, 11, "Block"),
      new Blocks(16, 11, "Block"),
      new Blocks(24, 11, "Block"),
      new Blocks(25, 11, "Block"),
      new Blocks(26, 11, "Block"),
      new Blocks(27, 11, "Block"),
      new Blocks(29, 11, "Block"),
      new Blocks(0, 12, "Lava"),
      new Blocks(1, 12, "Lava"),
      new Blocks(2, 12, "Lava"),
      new Blocks(3, 12, "Lava"),
      new Blocks(4, 12, "Lava"),
      new Blocks(5, 12, "Block"),
      new Blocks(14, 12, "Block"),
      new Blocks(16, 12, "Block"),
      new Blocks(27, 12, "Block"),
      new Blocks(28, 12, "LockedPortal", "", "LockedPortal", 15, 10),
      new Blocks(29, 12, "Block"),
      new Blocks(0, 13, "Block"),
      new Blocks(1, 13, "Block"),
      new Blocks(2, 13, "Block"),
      new Blocks(3, 13, "Block"),
      new Blocks(4, 13, "Block"),
      new Blocks(5, 13, "Block"),
      new Blocks(14, 13, "Block"),
      new Blocks(16, 13, "Block"),
      new Blocks(27, 13, "Block"),
      new Blocks(29, 13, "Block"),
      new Blocks(5, 14, "Block"),
      new Blocks(14, 14, "Block"),
      new Blocks(16, 14, "Block"),
      new Blocks(27, 14, "Block"),
      new Blocks(29, 14, "Block"),
      new Blocks(5, 15, "Block"),
      new Blocks(14, 15, "Block"),
      new Blocks(16, 15, "Block"),
      new Blocks(27, 15, "Block"),
      new Blocks(29, 15, "Block"),
      new Blocks(5, 16, "Block"),
      new Blocks(14, 16, "Block"),
      new Blocks(16, 16, "Block"),
      new Blocks(27, 16, "Block"),
      new Blocks(29, 16, "Block"),
      new Blocks(5, 17, "Block"),
      new Blocks(14, 17, "Block"),
      new Blocks(16, 17, "Block"),
      new Blocks(27, 17, "Block"),
      new Blocks(29, 17, "Block"),
      new Blocks(0, 18, "LockedPortal", "", "LockedPortal", 25, 10),
      new Blocks(3, 18, "Portal", "", "Portal", 2, 10),
      new Blocks(5, 18, "Block"),
      new Blocks(14, 18, "Block"),
      new Blocks(16, 18, "Block"),
      new Blocks(27, 18, "Block"),
      new Blocks(29, 18, "Block"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(14, 19, "Lava"),
      new Blocks(15, 19, "Lava"),
      new Blocks(16, 19, "Lava"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(3, 0, "Blue"),
      new Blocks(10, 0, "Red"),
      new Blocks(11, 0, "Red"),
      new Blocks(14, 0, "Blue"),
      new Blocks(17, 0, "Block"),
      new Blocks(3, 1, "Blue"),
      new Blocks(4, 1, "Blue"),
      new Blocks(5, 1, "Blue"),
      new Blocks(6, 1, "Blue"),
      new Blocks(7, 1, "Block"),
      new Blocks(10, 1, "Red"),
      new Blocks(11, 1, "Red"),
      new Blocks(14, 1, "Blue"),
      new Blocks(17, 1, "Block"),
      new Blocks(22, 1, "Red"),
      new Blocks(26, 1, "Block"),
      new Blocks(3, 2, "Red"),
      new Blocks(7, 2, "Block"),
      new Blocks(10, 2, "Red"),
      new Blocks(11, 2, "Red"),
      new Blocks(14, 2, "Blue"),
      new Blocks(17, 2, "Block"),
      new Blocks(19, 2, "Blue"),
      new Blocks(24, 2, "Blue"),
      new Blocks(26, 2, "Block"),
      new Blocks(3, 3, "Red"),
      new Blocks(7, 3, "Block"),
      new Blocks(8, 3, "Red"),
      new Blocks(9, 3, "Red"),
      new Blocks(10, 3, "Red"),
      new Blocks(11, 3, "Red"),
      new Blocks(12, 3, "Red"),
      new Blocks(13, 3, "Red"),
      new Blocks(14, 3, "Block"),
      new Blocks(15, 3, "Block"),
      new Blocks(17, 3, "Block"),
      new Blocks(26, 3, "Block"),
      new Blocks(0, 4, "Red"),
      new Blocks(1, 4, "Red"),
      new Blocks(2, 4, "Red"),
      new Blocks(3, 4, "Red"),
      new Blocks(7, 4, "Block"),
      new Blocks(14, 4, "Lava"),
      new Blocks(15, 4, "Lava"),
      new Blocks(17, 4, "Block"),
      new Blocks(20, 4, "Blue"),
      new Blocks(26, 4, "Block"),
      new Blocks(3, 5, "Blue"),
      new Blocks(7, 5, "Block"),
      new Blocks(14, 5, "Lava"),
      new Blocks(15, 5, "Lava"),
      new Blocks(17, 5, "Block"),
      new Blocks(18, 5, "Red"),
      new Blocks(23, 5, "Red"),
      new Blocks(26, 5, "Block"),
      new Blocks(3, 6, "Blue"),
      new Blocks(7, 6, "Block"),
      new Blocks(8, 6, "Blue"),
      new Blocks(9, 6, "Blue"),
      new Blocks(10, 6, "Blue"),
      new Blocks(11, 6, "Blue"),
      new Blocks(12, 6, "Blue"),
      new Blocks(13, 6, "Blue"),
      new Blocks(14, 6, "Lava"),
      new Blocks(15, 6, "Lava"),
      new Blocks(17, 6, "Block"),
      new Blocks(25, 6, "Blue"),
      new Blocks(26, 6, "Block"),
      new Blocks(3, 7, "Blue"),
      new Blocks(4, 7, "Blue"),
      new Blocks(5, 7, "Blue"),
      new Blocks(6, 7, "Blue"),
      new Blocks(7, 7, "Block"),
      new Blocks(14, 7, "Lava"),
      new Blocks(15, 7, "Lava"),
      new Blocks(17, 7, "Block"),
      new Blocks(20, 7, "Red"),
      new Blocks(26, 7, "Block"),
      new Blocks(3, 8, "Red"),
      new Blocks(7, 8, "Block"),
      new Blocks(14, 8, "Lava"),
      new Blocks(15, 8, "Lava"),
      new Blocks(17, 8, "Block"),
      new Blocks(22, 8, "Blue"),
      new Blocks(24, 8, "Red"),
      new Blocks(26, 8, "Block"),
      new Blocks(3, 9, "Red"),
      new Blocks(7, 9, "Block"),
      new Blocks(8, 9, "Red"),
      new Blocks(9, 9, "Red"),
      new Blocks(10, 9, "Red"),
      new Blocks(11, 9, "Red"),
      new Blocks(12, 9, "Red"),
      new Blocks(13, 9, "Red"),
      new Blocks(14, 9, "Lava"),
      new Blocks(15, 9, "Lava"),
      new Blocks(17, 9, "Block"),
      new Blocks(19, 9, "Blue"),
      new Blocks(26, 9, "Block"),
      new Blocks(0, 10, "Red"),
      new Blocks(1, 10, "Red"),
      new Blocks(2, 10, "Red"),
      new Blocks(3, 10, "Red"),
      new Blocks(7, 10, "Block"),
      new Blocks(14, 10, "Lava"),
      new Blocks(15, 10, "Lava"),
      new Blocks(17, 10, "Block"),
      new Blocks(21, 10, "Red"),
      new Blocks(26, 10, "Block"),
      new Blocks(3, 11, "Blue"),
      new Blocks(7, 11, "Block"),
      new Blocks(14, 11, "Lava"),
      new Blocks(15, 11, "Lava"),
      new Blocks(17, 11, "Block"),
      new Blocks(24, 11, "Red"),
      new Blocks(26, 11, "Block"),
      new Blocks(3, 12, "Blue"),
      new Blocks(7, 12, "Block"),
      new Blocks(8, 12, "Blue"),
      new Blocks(9, 12, "Blue"),
      new Blocks(10, 12, "Blue"),
      new Blocks(11, 12, "Blue"),
      new Blocks(12, 12, "Blue"),
      new Blocks(13, 12, "Blue"),
      new Blocks(14, 12, "Lava"),
      new Blocks(15, 12, "Lava"),
      new Blocks(17, 12, "Block"),
      new Blocks(26, 12, "Block"),
      new Blocks(3, 13, "Blue"),
      new Blocks(4, 13, "Blue"),
      new Blocks(5, 13, "Blue"),
      new Blocks(6, 13, "Blue"),
      new Blocks(7, 13, "Block"),
      new Blocks(14, 13, "Lava"),
      new Blocks(15, 13, "Lava"),
      new Blocks(17, 13, "Block"),
      new Blocks(19, 13, "Blue"),
      new Blocks(21, 13, "Red"),
      new Blocks(26, 13, "Block"),
      new Blocks(3, 14, "Red"),
      new Blocks(7, 14, "Block"),
      new Blocks(14, 14, "Lava"),
      new Blocks(15, 14, "Lava"),
      new Blocks(17, 14, "Block"),
      new Blocks(23, 14, "Blue"),
      new Blocks(26, 14, "Block"),
      new Blocks(3, 15, "Red"),
      new Blocks(7, 15, "Block"),
      new Blocks(8, 15, "Red"),
      new Blocks(9, 15, "Red"),
      new Blocks(10, 15, "Red"),
      new Blocks(11, 15, "Red"),
      new Blocks(12, 15, "Red"),
      new Blocks(13, 15, "Red"),
      new Blocks(14, 15, "Lava"),
      new Blocks(15, 15, "Lava"),
      new Blocks(17, 15, "Block"),
      new Blocks(26, 15, "Block"),
      new Blocks(0, 16, "Red"),
      new Blocks(1, 16, "Red"),
      new Blocks(2, 16, "Red"),
      new Blocks(3, 16, "Red"),
      new Blocks(7, 16, "Block"),
      new Blocks(14, 16, "Lava"),
      new Blocks(15, 16, "Lava"),
      new Blocks(25, 16, "Red"),
      new Blocks(26, 16, "Block"),
      new Blocks(7, 17, "Block"),
      new Blocks(14, 17, "Lava"),
      new Blocks(15, 17, "Lava"),
      new Blocks(19, 17, "Red"),
      new Blocks(22, 17, "Blue"),
      new Blocks(26, 17, "Block"),
      new Blocks(7, 18, "Block"),
      new Blocks(8, 18, "Lava"),
      new Blocks(9, 18, "Lava"),
      new Blocks(10, 18, "Lava"),
      new Blocks(11, 18, "Lava"),
      new Blocks(12, 18, "Lava"),
      new Blocks(13, 18, "Lava"),
      new Blocks(14, 18, "Lava"),
      new Blocks(15, 18, "Lava"),
      new Blocks(26, 18, "Block"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Speed", "Up"),
      new Blocks(17, 19, "Speed", "Up"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(8, 1, "Block", "Down"),
      new Blocks(14, 1, "Block", "Down"),
      new Blocks(18, 1, "Block", "Down"),
      new Blocks(24, 1, "Block", "Down"),
      new Blocks(4, 2, "Block", "Down"),
      new Blocks(12, 2, "Block", "Down"),
      new Blocks(6, 4, "Block", "Down"),
      new Blocks(16, 4, "Block", "Down"),
      new Blocks(22, 4, "Block", "Down"),
      new Blocks(26, 4, "Block"),
      new Blocks(20, 5, "Block", "Down"),
      new Blocks(26, 5, "Block"),
      new Blocks(26, 6, "Block"),
      new Blocks(10, 7, "Block", "Down"),
      new Blocks(16, 7, "Block", "Down"),
      new Blocks(26, 7, "Block"),
      new Blocks(24, 8, "Block", "Down"),
      new Blocks(26, 8, "Block"),
      new Blocks(4, 9, "Block", "Down"),
      new Blocks(14, 9, "Block", "Down"),
      new Blocks(18, 9, "Block", "Down"),
      new Blocks(26, 9, "Block"),
      new Blocks(8, 10, "Block", "Down"),
      new Blocks(26, 10, "Block"),
      new Blocks(22, 11, "Block", "Down"),
      new Blocks(26, 11, "Block"),
      new Blocks(26, 12, "Block"),
      new Blocks(26, 13, "Block"),
      new Blocks(6, 14, "Block", "Down"),
      new Blocks(12, 14, "Block", "Down"),
      new Blocks(18, 14, "Block", "Down"),
      new Blocks(26, 14, "Block"),
      new Blocks(14, 15, "Block", "Down"),
      new Blocks(26, 15, "Block"),
      new Blocks(10, 16, "Block", "Down"),
      new Blocks(24, 16, "Block", "Down"),
      new Blocks(26, 16, "Block"),
      new Blocks(4, 17, "Block", "Down"),
      new Blocks(16, 17, "Block", "Down"),
      new Blocks(26, 17, "Block"),
      new Blocks(6, 18, "Block", "Down"),
      new Blocks(20, 18, "Block", "Down"),
      new Blocks(26, 18, "Block"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(3, 0, "Block"),
      new Blocks(4, 0, "Portal", "", "Portal", 1, 19),
      new Blocks(5, 0, "Block"),
      new Blocks(6, 0, "Block"),
      new Blocks(7, 0, "Block"),
      new Blocks(8, 0, "Block"),
      new Blocks(9, 0, "Block"),
      new Blocks(10, 0, "Block"),
      new Blocks(11, 0, "Block"),
      new Blocks(12, 0, "Block"),
      new Blocks(13, 0, "Block"),
      new Blocks(14, 0, "Block"),
      new Blocks(15, 0, "Block"),
      new Blocks(16, 0, "Block"),
      new Blocks(17, 0, "Block"),
      new Blocks(18, 0, "Block"),
      new Blocks(19, 0, "Block"),
      new Blocks(20, 0, "Block"),
      new Blocks(21, 0, "Block"),
      new Blocks(22, 0, "Block"),
      new Blocks(23, 0, "Block"),
      new Blocks(24, 0, "Block"),
      new Blocks(25, 0, "Block"),
      new Blocks(26, 0, "Block"),
      new Blocks(3, 1, "Block"),
      new Blocks(5, 1, "Red"),
      new Blocks(15, 1, "Blue"),
      new Blocks(16, 1, "Blue"),
      new Blocks(17, 1, "Blue"),
      new Blocks(18, 1, "Blue"),
      new Blocks(19, 1, "Blue"),
      new Blocks(20, 1, "Blue"),
      new Blocks(21, 1, "Blue"),
      new Blocks(22, 1, "Blue"),
      new Blocks(23, 1, "Blue"),
      new Blocks(24, 1, "Blue"),
      new Blocks(25, 1, "Blue"),
      new Blocks(26, 1, "Block"),
      new Blocks(3, 2, "Block"),
      new Blocks(4, 2, "Blue"),
      new Blocks(5, 2, "Block"),
      new Blocks(6, 2, "Block"),
      new Blocks(7, 2, "Block"),
      new Blocks(8, 2, "Block"),
      new Blocks(9, 2, "Block"),
      new Blocks(10, 2, "Block"),
      new Blocks(11, 2, "Block"),
      new Blocks(12, 2, "Block"),
      new Blocks(13, 2, "Block"),
      new Blocks(14, 2, "Block"),
      new Blocks(15, 2, "Block"),
      new Blocks(16, 2, "Block"),
      new Blocks(17, 2, "Block"),
      new Blocks(18, 2, "Block"),
      new Blocks(19, 2, "Block"),
      new Blocks(20, 2, "Block"),
      new Blocks(21, 2, "Block"),
      new Blocks(22, 2, "Block"),
      new Blocks(23, 2, "Block"),
      new Blocks(24, 2, "Block"),
      new Blocks(26, 2, "Block"),
      new Blocks(3, 3, "Block"),
      new Blocks(5, 3, "Block"),
      new Blocks(6, 3, "Blue"),
      new Blocks(7, 3, "Blue"),
      new Blocks(8, 3, "Blue"),
      new Blocks(9, 3, "Blue"),
      new Blocks(10, 3, "Blue"),
      new Blocks(11, 3, "Blue"),
      new Blocks(13, 3, "Red"),
      new Blocks(14, 3, "Red"),
      new Blocks(15, 3, "Red"),
      new Blocks(16, 3, "Red"),
      new Blocks(17, 3, "Red"),
      new Blocks(18, 3, "Red"),
      new Blocks(19, 3, "Red"),
      new Blocks(20, 3, "Red"),
      new Blocks(21, 3, "Red"),
      new Blocks(22, 3, "Red"),
      new Blocks(23, 3, "Red"),
      new Blocks(24, 3, "Red"),
      new Blocks(25, 3, "Platform"),
      new Blocks(26, 3, "Block"),
      new Blocks(3, 4, "Block"),
      new Blocks(5, 4, "Block"),
      new Blocks(6, 4, "Blue"),
      new Blocks(7, 4, "Blue"),
      new Blocks(8, 4, "Blue"),
      new Blocks(9, 4, "Blue"),
      new Blocks(10, 4, "Blue"),
      new Blocks(11, 4, "Blue"),
      new Blocks(13, 4, "Red"),
      new Blocks(14, 4, "Red"),
      new Blocks(15, 4, "Red"),
      new Blocks(16, 4, "Red"),
      new Blocks(17, 4, "Red"),
      new Blocks(18, 4, "Red"),
      new Blocks(19, 4, "Red"),
      new Blocks(20, 4, "Red"),
      new Blocks(21, 4, "Red"),
      new Blocks(22, 4, "Red"),
      new Blocks(23, 4, "Red"),
      new Blocks(24, 4, "Red"),
      new Blocks(26, 4, "Block"),
      new Blocks(3, 5, "Block"),
      new Blocks(5, 5, "Block"),
      new Blocks(6, 5, "Blue"),
      new Blocks(7, 5, "Blue"),
      new Blocks(8, 5, "Blue"),
      new Blocks(9, 5, "Blue"),
      new Blocks(10, 5, "Blue"),
      new Blocks(11, 5, "Blue"),
      new Blocks(13, 5, "Red"),
      new Blocks(14, 5, "Red"),
      new Blocks(15, 5, "Red"),
      new Blocks(16, 5, "Red"),
      new Blocks(17, 5, "Red"),
      new Blocks(18, 5, "Red"),
      new Blocks(19, 5, "Red"),
      new Blocks(20, 5, "Red"),
      new Blocks(21, 5, "Red"),
      new Blocks(25, 5, "Portal", "", "Portal", 6, 13),
      new Blocks(26, 5, "Block"),
      new Blocks(3, 6, "Block"),
      new Blocks(5, 6, "Block"),
      new Blocks(6, 6, "Blue"),
      new Blocks(7, 6, "Blue"),
      new Blocks(8, 6, "Blue"),
      new Blocks(9, 6, "Blue"),
      new Blocks(10, 6, "Blue"),
      new Blocks(11, 6, "Blue"),
      new Blocks(12, 6, "Block"),
      new Blocks(13, 6, "Blue"),
      new Blocks(14, 6, "Blue"),
      new Blocks(15, 6, "Blue"),
      new Blocks(16, 6, "Blue"),
      new Blocks(17, 6, "Blue"),
      new Blocks(18, 6, "Blue"),
      new Blocks(19, 6, "Blue"),
      new Blocks(20, 6, "Blue"),
      new Blocks(21, 6, "Blue"),
      new Blocks(22, 6, "Blue"),
      new Blocks(23, 6, "Blue"),
      new Blocks(24, 6, "Blue"),
      new Blocks(25, 6, "Blue"),
      new Blocks(26, 6, "Block"),
      new Blocks(3, 7, "Block"),
      new Blocks(5, 7, "Block"),
      new Blocks(6, 7, "Blue"),
      new Blocks(7, 7, "Blue"),
      new Blocks(8, 7, "Blue"),
      new Blocks(9, 7, "Blue"),
      new Blocks(10, 7, "Blue"),
      new Blocks(11, 7, "Blue"),
      new Blocks(12, 7, "Block"),
      new Blocks(13, 7, "Blue"),
      new Blocks(14, 7, "Blue"),
      new Blocks(15, 7, "Blue"),
      new Blocks(16, 7, "Blue"),
      new Blocks(17, 7, "Blue"),
      new Blocks(18, 7, "Blue"),
      new Blocks(19, 7, "Blue"),
      new Blocks(20, 7, "Blue"),
      new Blocks(21, 7, "Blue"),
      new Blocks(22, 7, "Blue"),
      new Blocks(23, 7, "Blue"),
      new Blocks(24, 7, "Blue"),
      new Blocks(25, 7, "Blue"),
      new Blocks(26, 7, "Block"),
      new Blocks(3, 8, "Block"),
      new Blocks(5, 8, "Block"),
      new Blocks(6, 8, "Blue"),
      new Blocks(7, 8, "Block"),
      new Blocks(8, 8, "Block"),
      new Blocks(9, 8, "Block"),
      new Blocks(10, 8, "Block"),
      new Blocks(11, 8, "Block"),
      new Blocks(12, 8, "Block"),
      new Blocks(13, 8, "Blue"),
      new Blocks(14, 8, "Blue"),
      new Blocks(15, 8, "Blue"),
      new Blocks(16, 8, "Blue"),
      new Blocks(17, 8, "Blue"),
      new Blocks(18, 8, "Blue"),
      new Blocks(19, 8, "Blue"),
      new Blocks(20, 8, "Blue"),
      new Blocks(21, 8, "Blue"),
      new Blocks(22, 8, "Blue"),
      new Blocks(23, 8, "Blue"),
      new Blocks(24, 8, "Blue"),
      new Blocks(25, 8, "Blue"),
      new Blocks(26, 8, "Block"),
      new Blocks(3, 9, "Block"),
      new Blocks(5, 9, "Block"),
      new Blocks(7, 9, "Red"),
      new Blocks(8, 9, "Red"),
      new Blocks(9, 9, "Red"),
      new Blocks(10, 9, "Red"),
      new Blocks(11, 9, "Red"),
      new Blocks(26, 9, "Block"),
      new Blocks(3, 10, "Block"),
      new Blocks(5, 10, "Block"),
      new Blocks(6, 10, "Block"),
      new Blocks(7, 10, "Speed", "Right"),
      new Blocks(8, 10, "Speed", "Right"),
      new Blocks(9, 10, "Speed", "Right"),
      new Blocks(10, 10, "Speed", "Right"),
      new Blocks(11, 10, "Speed", "Right"),
      new Blocks(12, 10, "Block"),
      new Blocks(13, 10, "Block"),
      new Blocks(14, 10, "Block"),
      new Blocks(15, 10, "Block"),
      new Blocks(16, 10, "Block"),
      new Blocks(17, 10, "Block"),
      new Blocks(18, 10, "Block"),
      new Blocks(19, 10, "Block"),
      new Blocks(20, 10, "Block"),
      new Blocks(21, 10, "Block"),
      new Blocks(22, 10, "Block"),
      new Blocks(23, 10, "Block"),
      new Blocks(24, 10, "Block"),
      new Blocks(25, 10, "Block"),
      new Blocks(26, 10, "Block"),
      new Blocks(3, 11, "Block"),
      new Blocks(5, 11, "Block"),
      new Blocks(6, 11, "Blue"),
      new Blocks(8, 11, "Red"),
      new Blocks(9, 11, "Red"),
      new Blocks(10, 11, "Blue"),
      new Blocks(11, 11, "Blue"),
      new Blocks(12, 11, "Blue"),
      new Blocks(14, 11, "Red"),
      new Blocks(15, 11, "Red"),
      new Blocks(16, 11, "Blue"),
      new Blocks(17, 11, "Blue"),
      new Blocks(18, 11, "Blue"),
      new Blocks(20, 11, "Red"),
      new Blocks(21, 11, "Red"),
      new Blocks(22, 11, "Blue"),
      new Blocks(23, 11, "Blue"),
      new Blocks(24, 11, "Blue"),
      new Blocks(26, 11, "Block"),
      new Blocks(3, 12, "Block"),
      new Blocks(5, 12, "Block"),
      new Blocks(6, 12, "Blue"),
      new Blocks(7, 12, "Red"),
      new Blocks(8, 12, "Red"),
      new Blocks(9, 12, "Red"),
      new Blocks(11, 12, "Blue"),
      new Blocks(12, 12, "Blue"),
      new Blocks(13, 12, "Red"),
      new Blocks(14, 12, "Red"),
      new Blocks(15, 12, "Red"),
      new Blocks(17, 12, "Blue"),
      new Blocks(18, 12, "Blue"),
      new Blocks(19, 12, "Red"),
      new Blocks(20, 12, "Red"),
      new Blocks(21, 12, "Red"),
      new Blocks(23, 12, "Blue"),
      new Blocks(24, 12, "Blue"),
      new Blocks(26, 12, "Block"),
      new Blocks(3, 13, "Block"),
      new Blocks(5, 13, "Block"),
      new Blocks(6, 13, "Portal", "", "Portal", 25, 5),
      new Blocks(7, 13, "Blue"),
      new Blocks(8, 13, "Red"),
      new Blocks(9, 13, "Red"),
      new Blocks(10, 13, "Blue"),
      new Blocks(11, 13, "Blue"),
      new Blocks(12, 13, "Blue"),
      new Blocks(13, 13, "Red"),
      new Blocks(14, 13, "Red"),
      new Blocks(15, 13, "Red"),
      new Blocks(16, 13, "Blue"),
      new Blocks(17, 13, "Blue"),
      new Blocks(18, 13, "Blue"),
      new Blocks(19, 13, "Red"),
      new Blocks(20, 13, "Red"),
      new Blocks(21, 13, "Red"),
      new Blocks(22, 13, "Blue"),
      new Blocks(23, 13, "Blue"),
      new Blocks(24, 13, "Blue"),
      new Blocks(26, 13, "Block"),
      new Blocks(3, 14, "Block"),
      new Blocks(5, 14, "Block"),
      new Blocks(7, 14, "Blue"),
      new Blocks(8, 14, "Red"),
      new Blocks(9, 14, "Red"),
      new Blocks(10, 14, "Blue"),
      new Blocks(11, 14, "Blue"),
      new Blocks(12, 14, "Blue"),
      new Blocks(13, 14, "Red"),
      new Blocks(14, 14, "Red"),
      new Blocks(15, 14, "Red"),
      new Blocks(16, 14, "Blue"),
      new Blocks(17, 14, "Blue"),
      new Blocks(18, 14, "Blue"),
      new Blocks(19, 14, "Red"),
      new Blocks(20, 14, "Red"),
      new Blocks(21, 14, "Red"),
      new Blocks(22, 14, "Blue"),
      new Blocks(23, 14, "Blue"),
      new Blocks(24, 14, "Blue"),
      new Blocks(25, 14, "LockedPortal", "", "LockedPortal", 6, 16),
      new Blocks(26, 14, "Block"),
      new Blocks(3, 15, "Block"),
      new Blocks(5, 15, "Block"),
      new Blocks(6, 15, "Block"),
      new Blocks(7, 15, "Block"),
      new Blocks(8, 15, "Block"),
      new Blocks(9, 15, "Block"),
      new Blocks(10, 15, "Block"),
      new Blocks(11, 15, "Block"),
      new Blocks(12, 15, "Block"),
      new Blocks(13, 15, "Block"),
      new Blocks(14, 15, "Block"),
      new Blocks(15, 15, "Block"),
      new Blocks(16, 15, "Block"),
      new Blocks(17, 15, "Block"),
      new Blocks(18, 15, "Block"),
      new Blocks(19, 15, "Block"),
      new Blocks(20, 15, "Block"),
      new Blocks(21, 15, "Block"),
      new Blocks(22, 15, "Block"),
      new Blocks(23, 15, "Block"),
      new Blocks(24, 15, "Block"),
      new Blocks(25, 15, "Block"),
      new Blocks(26, 15, "Block"),
      new Blocks(3, 16, "Block"),
      new Blocks(5, 16, "Block"),
      new Blocks(6, 16, "LockedPortal", "", "LockedPortal", 25, 14),
      new Blocks(7, 16, "Blue"),
      new Blocks(8, 16, "Blue"),
      new Blocks(9, 16, "Blue"),
      new Blocks(10, 16, "Blue"),
      new Blocks(11, 16, "Blue"),
      new Blocks(15, 16, "Blue"),
      new Blocks(16, 16, "Blue"),
      new Blocks(17, 16, "Blue"),
      new Blocks(18, 16, "Blue"),
      new Blocks(19, 16, "Blue"),
      new Blocks(20, 16, "Blue"),
      new Blocks(21, 16, "Blue"),
      new Blocks(22, 16, "Blue"),
      new Blocks(23, 16, "Blue"),
      new Blocks(24, 16, "Blue"),
      new Blocks(26, 16, "Block"),
      new Blocks(1, 17, "Portal", "", "Portal", 28, 19),
      new Blocks(3, 17, "Block"),
      new Blocks(5, 17, "Block"),
      new Blocks(6, 17, "Block"),
      new Blocks(7, 17, "Speed", "Right"),
      new Blocks(8, 17, "Speed", "Right"),
      new Blocks(9, 17, "Speed", "Right"),
      new Blocks(10, 17, "Speed", "Right"),
      new Blocks(11, 17, "Speed", "Right"),
      new Blocks(12, 17, "Block"),
      new Blocks(13, 17, "Block"),
      new Blocks(14, 17, "Platform"),
      new Blocks(15, 17, "Block"),
      new Blocks(16, 17, "Block"),
      new Blocks(17, 17, "Block"),
      new Blocks(18, 17, "Block"),
      new Blocks(19, 17, "Block"),
      new Blocks(20, 17, "Block"),
      new Blocks(21, 17, "Block"),
      new Blocks(22, 17, "Block"),
      new Blocks(23, 17, "Block"),
      new Blocks(24, 17, "Block"),
      new Blocks(26, 17, "Block"),
      new Blocks(3, 18, "Block"),
      new Blocks(5, 18, "Red"),
      new Blocks(6, 18, "Red"),
      new Blocks(7, 18, "Red"),
      new Blocks(8, 18, "Red"),
      new Blocks(9, 18, "Red"),
      new Blocks(10, 18, "Red"),
      new Blocks(11, 18, "Red"),
      new Blocks(12, 18, "Red"),
      new Blocks(13, 18, "Red"),
      new Blocks(14, 18, "Red"),
      new Blocks(15, 18, "Block"),
      new Blocks(16, 18, "Key", "", "Key"),
      new Blocks(17, 18, "Blue"),
      new Blocks(18, 18, "Blue"),
      new Blocks(19, 18, "Blue"),
      new Blocks(20, 18, "Blue"),
      new Blocks(26, 18, "Block"),
      new Blocks(1, 19, "Portal", "", "Portal", 4, 0),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Speed", "Right"),
      new Blocks(18, 19, "Speed", "Right"),
      new Blocks(19, 19, "Speed", "Right"),
      new Blocks(20, 19, "Speed", "Right"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(28, 19, "Portal", "", "Portal", 1, 17),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(26, 0, "Block"),
      new Blocks(26, 1, "Block"),
      new Blocks(28, 1, "LockedPortal", "", "LockedPortal", 24, 18),
      new Blocks(26, 2, "Block"),
      new Blocks(25, 3, "Key", "", "Key"),
      new Blocks(26, 3, "Block"),
      new Blocks(27, 3, "Red"),
      new Blocks(28, 3, "Platform"),
      new Blocks(29, 3, "Red"),
      new Blocks(11, 4, "Block"),
      new Blocks(12, 4, "Block"),
      new Blocks(13, 4, "Block"),
      new Blocks(23, 4, "Block"),
      new Blocks(24, 4, "Block"),
      new Blocks(25, 4, "Block"),
      new Blocks(26, 4, "Block"),
      new Blocks(27, 4, "Blue"),
      new Blocks(28, 4, "Blue"),
      new Blocks(29, 4, "Platform"),
      new Blocks(0, 5, "Platform"),
      new Blocks(1, 5, "Platform"),
      new Blocks(26, 5, "Block"),
      new Blocks(27, 5, "Platform"),
      new Blocks(28, 5, "Red"),
      new Blocks(29, 5, "Red"),
      new Blocks(26, 6, "Block"),
      new Blocks(27, 6, "Blue"),
      new Blocks(28, 6, "Blue"),
      new Blocks(29, 6, "Platform"),
      new Blocks(0, 7, "Portal", "", "Portal", 25, 9),
      new Blocks(26, 7, "Block"),
      new Blocks(27, 7, "Red"),
      new Blocks(28, 7, "Platform"),
      new Blocks(29, 7, "Red"),
      new Blocks(0, 8, "Block"),
      new Blocks(1, 8, "Block"),
      new Blocks(2, 8, "Block"),
      new Blocks(3, 8, "Block"),
      new Blocks(4, 8, "Block"),
      new Blocks(5, 8, "Block"),
      new Blocks(6, 8, "Block"),
      new Blocks(7, 8, "Block"),
      new Blocks(8, 8, "Block"),
      new Blocks(9, 8, "Block"),
      new Blocks(10, 8, "Block"),
      new Blocks(11, 8, "Block"),
      new Blocks(12, 8, "Block"),
      new Blocks(13, 8, "Block"),
      new Blocks(14, 8, "Block"),
      new Blocks(15, 8, "Block"),
      new Blocks(16, 8, "Block"),
      new Blocks(17, 8, "Block"),
      new Blocks(18, 8, "Block"),
      new Blocks(19, 8, "Block"),
      new Blocks(20, 8, "Block"),
      new Blocks(21, 8, "Block"),
      new Blocks(22, 8, "Block"),
      new Blocks(23, 8, "Block"),
      new Blocks(24, 8, "Block"),
      new Blocks(25, 8, "Block"),
      new Blocks(26, 8, "Block"),
      new Blocks(27, 8, "Blue"),
      new Blocks(28, 8, "Blue"),
      new Blocks(29, 8, "Platform"),
      new Blocks(0, 9, "Portal", "", "Portal", 4, 15),
      new Blocks(25, 9, "Portal", "", "Portal", 0, 7),
      new Blocks(26, 9, "Block"),
      new Blocks(27, 9, "Platform"),
      new Blocks(28, 9, "Red"),
      new Blocks(29, 9, "Red"),
      new Blocks(0, 10, "Block"),
      new Blocks(1, 10, "Speed", "Left"),
      new Blocks(2, 10, "Speed", "Left"),
      new Blocks(3, 10, "Speed", "Left"),
      new Blocks(4, 10, "Speed", "Left"),
      new Blocks(5, 10, "Speed", "Left"),
      new Blocks(6, 10, "Speed", "Left"),
      new Blocks(7, 10, "Speed", "Left"),
      new Blocks(8, 10, "Speed", "Left"),
      new Blocks(9, 10, "Speed", "Left"),
      new Blocks(10, 10, "Speed", "Left"),
      new Blocks(11, 10, "Speed", "Left"),
      new Blocks(12, 10, "Speed", "Left"),
      new Blocks(13, 10, "Speed", "Left"),
      new Blocks(14, 10, "Speed", "Left"),
      new Blocks(15, 10, "Speed", "Left"),
      new Blocks(16, 10, "Speed", "Left"),
      new Blocks(17, 10, "Speed", "Left"),
      new Blocks(18, 10, "Speed", "Left"),
      new Blocks(19, 10, "Speed", "Left"),
      new Blocks(20, 10, "Speed", "Left"),
      new Blocks(21, 10, "Speed", "Left"),
      new Blocks(22, 10, "Speed", "Left"),
      new Blocks(23, 10, "Speed", "Left"),
      new Blocks(24, 10, "Speed", "Left"),
      new Blocks(25, 10, "Block"),
      new Blocks(26, 10, "Block"),
      new Blocks(27, 10, "Blue"),
      new Blocks(28, 10, "Platform"),
      new Blocks(29, 10, "Blue"),
      new Blocks(0, 11, "Block"),
      new Blocks(1, 11, "Block"),
      new Blocks(2, 11, "Block"),
      new Blocks(3, 11, "Block"),
      new Blocks(4, 11, "Block"),
      new Blocks(5, 11, "Block"),
      new Blocks(6, 11, "Block"),
      new Blocks(7, 11, "Block"),
      new Blocks(8, 11, "Block"),
      new Blocks(9, 11, "Block"),
      new Blocks(10, 11, "Block"),
      new Blocks(11, 11, "Block"),
      new Blocks(12, 11, "Block"),
      new Blocks(13, 11, "Block"),
      new Blocks(14, 11, "Block"),
      new Blocks(15, 11, "Block"),
      new Blocks(16, 11, "Block"),
      new Blocks(17, 11, "Block"),
      new Blocks(18, 11, "Block"),
      new Blocks(19, 11, "Block"),
      new Blocks(20, 11, "Block"),
      new Blocks(21, 11, "Block"),
      new Blocks(22, 11, "Block"),
      new Blocks(23, 11, "Block"),
      new Blocks(24, 11, "Block"),
      new Blocks(25, 11, "Block"),
      new Blocks(26, 11, "Block"),
      new Blocks(27, 11, "Red"),
      new Blocks(28, 11, "Red"),
      new Blocks(29, 11, "Platform"),
      new Blocks(26, 12, "Block"),
      new Blocks(27, 12, "Platform"),
      new Blocks(28, 12, "Blue"),
      new Blocks(29, 12, "Blue"),
      new Blocks(1, 13, "Platform"),
      new Blocks(2, 13, "Block"),
      new Blocks(3, 13, "Block"),
      new Blocks(4, 13, "Block"),
      new Blocks(5, 13, "Lava"),
      new Blocks(6, 13, "Lava"),
      new Blocks(7, 13, "Block"),
      new Blocks(8, 13, "Block"),
      new Blocks(9, 13, "Block"),
      new Blocks(10, 13, "Block"),
      new Blocks(11, 13, "Block"),
      new Blocks(12, 13, "Lava"),
      new Blocks(13, 13, "Lava"),
      new Blocks(14, 13, "Block"),
      new Blocks(15, 13, "Block"),
      new Blocks(16, 13, "Block"),
      new Blocks(17, 13, "Block"),
      new Blocks(18, 13, "Block"),
      new Blocks(19, 13, "Lava"),
      new Blocks(20, 13, "Lava"),
      new Blocks(21, 13, "Block"),
      new Blocks(22, 13, "Block"),
      new Blocks(23, 13, "Block"),
      new Blocks(26, 13, "Block"),
      new Blocks(27, 13, "Red"),
      new Blocks(28, 13, "Red"),
      new Blocks(29, 13, "Platform"),
      new Blocks(2, 14, "Block"),
      new Blocks(3, 14, "Lava"),
      new Blocks(4, 14, "Lava"),
      new Blocks(5, 14, "Lava"),
      new Blocks(6, 14, "Block"),
      new Blocks(7, 14, "Lava"),
      new Blocks(8, 14, "Block"),
      new Blocks(9, 14, "Lava"),
      new Blocks(10, 14, "Block"),
      new Blocks(11, 14, "Lava"),
      new Blocks(12, 14, "Block"),
      new Blocks(13, 14, "Lava"),
      new Blocks(14, 14, "Block"),
      new Blocks(15, 14, "Lava"),
      new Blocks(16, 14, "Block"),
      new Blocks(17, 14, "Lava"),
      new Blocks(18, 14, "Block"),
      new Blocks(19, 14, "Lava"),
      new Blocks(20, 14, "Block"),
      new Blocks(21, 14, "Lava"),
      new Blocks(22, 14, "Block"),
      new Blocks(23, 14, "Lava"),
      new Blocks(26, 14, "Block"),
      new Blocks(27, 14, "Blue"),
      new Blocks(28, 14, "Platform"),
      new Blocks(29, 14, "Blue"),
      new Blocks(2, 15, "Block"),
      new Blocks(3, 15, "Block"),
      new Blocks(4, 15, "Portal", "", "Portal", 0, 9),
      new Blocks(26, 15, "Block"),
      new Blocks(27, 15, "Red"),
      new Blocks(28, 15, "Red"),
      new Blocks(29, 15, "Platform"),
      new Blocks(2, 16, "Block"),
      new Blocks(3, 16, "Block"),
      new Blocks(4, 16, "Block"),
      new Blocks(5, 16, "Block"),
      new Blocks(6, 16, "Lava"),
      new Blocks(7, 16, "Block"),
      new Blocks(8, 16, "Lava"),
      new Blocks(9, 16, "Block"),
      new Blocks(10, 16, "Lava"),
      new Blocks(11, 16, "Block"),
      new Blocks(12, 16, "Lava"),
      new Blocks(13, 16, "Block"),
      new Blocks(14, 16, "Lava"),
      new Blocks(15, 16, "Block"),
      new Blocks(16, 16, "Lava"),
      new Blocks(17, 16, "Block"),
      new Blocks(18, 16, "Lava"),
      new Blocks(19, 16, "Block"),
      new Blocks(20, 16, "Lava"),
      new Blocks(21, 16, "Block"),
      new Blocks(22, 16, "Lava"),
      new Blocks(23, 16, "Block"),
      new Blocks(24, 16, "Block"),
      new Blocks(25, 16, "Block"),
      new Blocks(26, 16, "Block"),
      new Blocks(27, 16, "Platform"),
      new Blocks(28, 16, "Blue"),
      new Blocks(29, 16, "Blue"),
      new Blocks(2, 17, "Block"),
      new Blocks(3, 17, "Lava"),
      new Blocks(4, 17, "Lava"),
      new Blocks(5, 17, "Lava"),
      new Blocks(6, 17, "Lava"),
      new Blocks(7, 17, "Lava"),
      new Blocks(8, 17, "Lava"),
      new Blocks(9, 17, "Lava"),
      new Blocks(10, 17, "Lava"),
      new Blocks(11, 17, "Lava"),
      new Blocks(12, 17, "Lava"),
      new Blocks(13, 17, "Lava"),
      new Blocks(14, 17, "Lava"),
      new Blocks(15, 17, "Lava"),
      new Blocks(16, 17, "Lava"),
      new Blocks(17, 17, "Lava"),
      new Blocks(18, 17, "Lava"),
      new Blocks(19, 17, "Lava"),
      new Blocks(20, 17, "Lava"),
      new Blocks(21, 17, "Lava"),
      new Blocks(22, 17, "Lava"),
      new Blocks(23, 17, "Lava"),
      new Blocks(24, 17, "Lava"),
      new Blocks(25, 17, "Lava"),
      new Blocks(26, 17, "Block"),
      new Blocks(4, 18, "Blue"),
      new Blocks(6, 18, "Blue"),
      new Blocks(8, 18, "Blue"),
      new Blocks(10, 18, "Blue"),
      new Blocks(12, 18, "Blue"),
      new Blocks(14, 18, "Blue"),
      new Blocks(16, 18, "Blue"),
      new Blocks(18, 18, "Blue"),
      new Blocks(20, 18, "Blue"),
      new Blocks(22, 18, "Blue"),
      new Blocks(24, 18, "LockedPortal", "", "LockedPortal", 28, 1),
      new Blocks(26, 18, "Block"),
      new Blocks(0, 19, "Speed", "Up"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Block"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(0, 0, "Lava"),
      new Blocks(1, 0, "Lava"),
      new Blocks(2, 0, "Lava"),
      new Blocks(3, 0, "Lava"),
      new Blocks(4, 0, "Lava"),
      new Blocks(5, 0, "Lava"),
      new Blocks(6, 0, "Lava"),
      new Blocks(7, 0, "Lava"),
      new Blocks(8, 0, "Lava"),
      new Blocks(9, 0, "Lava"),
      new Blocks(10, 0, "Lava"),
      new Blocks(11, 0, "Lava"),
      new Blocks(12, 0, "Lava"),
      new Blocks(13, 0, "Lava"),
      new Blocks(14, 0, "Lava"),
      new Blocks(15, 0, "Lava"),
      new Blocks(16, 0, "Lava"),
      new Blocks(17, 0, "Lava"),
      new Blocks(18, 0, "Lava"),
      new Blocks(19, 0, "Lava"),
      new Blocks(20, 0, "Lava"),
      new Blocks(21, 0, "Lava"),
      new Blocks(22, 0, "Lava"),
      new Blocks(23, 0, "Lava"),
      new Blocks(24, 0, "Lava"),
      new Blocks(25, 0, "Lava"),
      new Blocks(26, 0, "Lava"),
      new Blocks(27, 0, "Lava"),
      new Blocks(28, 0, "Lava"),
      new Blocks(29, 0, "Lava"),
      new Blocks(0, 1, "Lava"),
      new Blocks(4, 1, "Lava"),
      new Blocks(8, 1, "Lava"),
      new Blocks(12, 1, "Lava"),
      new Blocks(16, 1, "Lava"),
      new Blocks(20, 1, "Lava"),
      new Blocks(24, 1, "Lava"),
      new Blocks(29, 1, "Lava"),
      new Blocks(0, 2, "Lava"),
      new Blocks(2, 2, "Portal", "", "Portal", 6, 17),
      new Blocks(4, 2, "Lava"),
      new Blocks(6, 2, "Portal", "", "Portal", 10, 17),
      new Blocks(8, 2, "Lava"),
      new Blocks(10, 2, "Portal", "", "Portal", 14, 17),
      new Blocks(12, 2, "Lava"),
      new Blocks(14, 2, "Portal", "", "Portal", 18, 17),
      new Blocks(16, 2, "Lava"),
      new Blocks(18, 2, "Portal", "", "Portal", 22, 17),
      new Blocks(20, 2, "Lava"),
      new Blocks(22, 2, "Portal", "", "Portal", 26, 3),
      new Blocks(24, 2, "Lava"),
      new Blocks(29, 2, "Lava"),
      new Blocks(0, 3, "Lava"),
      new Blocks(4, 3, "Lava"),
      new Blocks(8, 3, "Lava"),
      new Blocks(12, 3, "Lava"),
      new Blocks(16, 3, "Lava"),
      new Blocks(20, 3, "Lava"),
      new Blocks(24, 3, "Lava"),
      new Blocks(26, 3, "Portal", "", "Portal", 22, 2),
      new Blocks(29, 3, "Lava"),
      new Blocks(0, 4, "Lava"),
      new Blocks(3, 4, "Speed", "Left"),
      new Blocks(4, 4, "Lava"),
      new Blocks(5, 4, "Speed", "Right"),
      new Blocks(8, 4, "Lava"),
      new Blocks(11, 4, "Speed", "Left"),
      new Blocks(12, 4, "Lava"),
      new Blocks(13, 4, "Speed", "Right"),
      new Blocks(16, 4, "Lava"),
      new Blocks(19, 4, "Speed", "Left"),
      new Blocks(20, 4, "Lava"),
      new Blocks(21, 4, "Speed", "Right"),
      new Blocks(24, 4, "Lava"),
      new Blocks(29, 4, "Lava"),
      new Blocks(0, 5, "Lava"),
      new Blocks(4, 5, "Lava"),
      new Blocks(8, 5, "Lava"),
      new Blocks(12, 5, "Lava"),
      new Blocks(16, 5, "Lava"),
      new Blocks(20, 5, "Lava"),
      new Blocks(24, 5, "Lava"),
      new Blocks(26, 5, "Speed", "Left"),
      new Blocks(27, 5, "Speed", "Left"),
      new Blocks(28, 5, "Speed", "Left"),
      new Blocks(29, 5, "Lava"),
      new Blocks(0, 6, "Lava"),
      new Blocks(4, 6, "Lava"),
      new Blocks(8, 6, "Lava"),
      new Blocks(12, 6, "Lava"),
      new Blocks(16, 6, "Lava"),
      new Blocks(20, 6, "Lava"),
      new Blocks(24, 6, "Lava"),
      new Blocks(29, 6, "Lava"),
      new Blocks(0, 7, "Lava"),
      new Blocks(1, 7, "Speed", "Right"),
      new Blocks(4, 7, "Lava"),
      new Blocks(7, 7, "Speed", "Left"),
      new Blocks(8, 7, "Lava"),
      new Blocks(9, 7, "Speed", "Right"),
      new Blocks(12, 7, "Lava"),
      new Blocks(15, 7, "Speed", "Left"),
      new Blocks(16, 7, "Lava"),
      new Blocks(17, 7, "Speed", "Right"),
      new Blocks(20, 7, "Lava"),
      new Blocks(23, 7, "Speed", "Left"),
      new Blocks(24, 7, "Lava"),
      new Blocks(25, 7, "Speed", "Right"),
      new Blocks(26, 7, "Speed", "Right"),
      new Blocks(27, 7, "Speed", "Right"),
      new Blocks(29, 7, "Lava"),
      new Blocks(0, 8, "Lava"),
      new Blocks(4, 8, "Lava"),
      new Blocks(8, 8, "Lava"),
      new Blocks(12, 8, "Lava"),
      new Blocks(16, 8, "Lava"),
      new Blocks(20, 8, "Lava"),
      new Blocks(24, 8, "Lava"),
      new Blocks(29, 8, "Lava"),
      new Blocks(0, 9, "Lava"),
      new Blocks(4, 9, "Lava"),
      new Blocks(8, 9, "Lava"),
      new Blocks(12, 9, "Lava"),
      new Blocks(16, 9, "Lava"),
      new Blocks(20, 9, "Lava"),
      new Blocks(24, 9, "Lava"),
      new Blocks(26, 9, "Speed", "Left"),
      new Blocks(27, 9, "Speed", "Left"),
      new Blocks(28, 9, "Speed", "Left"),
      new Blocks(29, 9, "Lava"),
      new Blocks(0, 10, "Lava"),
      new Blocks(3, 10, "Speed", "Left"),
      new Blocks(4, 10, "Lava"),
      new Blocks(5, 10, "Speed", "Right"),
      new Blocks(8, 10, "Lava"),
      new Blocks(11, 10, "Speed", "Left"),
      new Blocks(12, 10, "Lava"),
      new Blocks(13, 10, "Speed", "Right"),
      new Blocks(16, 10, "Lava"),
      new Blocks(19, 10, "Speed", "Left"),
      new Blocks(20, 10, "Lava"),
      new Blocks(21, 10, "Speed", "Right"),
      new Blocks(24, 10, "Lava"),
      new Blocks(29, 10, "Lava"),
      new Blocks(0, 11, "Lava"),
      new Blocks(4, 11, "Lava"),
      new Blocks(8, 11, "Lava"),
      new Blocks(12, 11, "Lava"),
      new Blocks(16, 11, "Lava"),
      new Blocks(20, 11, "Lava"),
      new Blocks(24, 11, "Lava"),
      new Blocks(25, 11, "Speed", "Right"),
      new Blocks(26, 11, "Speed", "Right"),
      new Blocks(27, 11, "Speed", "Right"),
      new Blocks(29, 11, "Lava"),
      new Blocks(0, 12, "Lava"),
      new Blocks(4, 12, "Lava"),
      new Blocks(8, 12, "Lava"),
      new Blocks(12, 12, "Lava"),
      new Blocks(16, 12, "Lava"),
      new Blocks(20, 12, "Lava"),
      new Blocks(24, 12, "Lava"),
      new Blocks(29, 12, "Lava"),
      new Blocks(0, 13, "Lava"),
      new Blocks(1, 13, "Speed", "Right"),
      new Blocks(4, 13, "Lava"),
      new Blocks(7, 13, "Speed", "Left"),
      new Blocks(8, 13, "Lava"),
      new Blocks(9, 13, "Speed", "Right"),
      new Blocks(12, 13, "Lava"),
      new Blocks(15, 13, "Speed", "Left"),
      new Blocks(16, 13, "Lava"),
      new Blocks(17, 13, "Speed", "Right"),
      new Blocks(20, 13, "Lava"),
      new Blocks(23, 13, "Speed", "Left"),
      new Blocks(24, 13, "Lava"),
      new Blocks(26, 13, "Speed", "Left"),
      new Blocks(27, 13, "Speed", "Left"),
      new Blocks(28, 13, "Speed", "Left"),
      new Blocks(29, 13, "Lava"),
      new Blocks(0, 14, "Lava"),
      new Blocks(4, 14, "Lava"),
      new Blocks(8, 14, "Lava"),
      new Blocks(12, 14, "Lava"),
      new Blocks(16, 14, "Lava"),
      new Blocks(20, 14, "Lava"),
      new Blocks(24, 14, "Lava"),
      new Blocks(29, 14, "Lava"),
      new Blocks(0, 15, "Lava"),
      new Blocks(4, 15, "Lava"),
      new Blocks(8, 15, "Lava"),
      new Blocks(12, 15, "Lava"),
      new Blocks(16, 15, "Lava"),
      new Blocks(20, 15, "Lava"),
      new Blocks(24, 15, "Lava"),
      new Blocks(25, 15, "Speed", "Right"),
      new Blocks(26, 15, "Speed", "Right"),
      new Blocks(27, 15, "Speed", "Right"),
      new Blocks(29, 15, "Lava"),
      new Blocks(0, 16, "Lava"),
      new Blocks(3, 16, "Speed", "Left"),
      new Blocks(4, 16, "Lava"),
      new Blocks(5, 16, "Speed", "Right"),
      new Blocks(8, 16, "Lava"),
      new Blocks(11, 16, "Speed", "Left"),
      new Blocks(12, 16, "Lava"),
      new Blocks(13, 16, "Speed", "Right"),
      new Blocks(16, 16, "Lava"),
      new Blocks(19, 16, "Speed", "Left"),
      new Blocks(20, 16, "Lava"),
      new Blocks(21, 16, "Speed", "Right"),
      new Blocks(24, 16, "Lava"),
      new Blocks(29, 16, "Lava"),
      new Blocks(0, 17, "Lava"),
      new Blocks(4, 17, "Lava"),
      new Blocks(6, 17, "Portal", "", "Portal", 2, 2),
      new Blocks(8, 17, "Lava"),
      new Blocks(10, 17, "Portal", "", "Portal", 6, 2),
      new Blocks(12, 17, "Lava"),
      new Blocks(14, 17, "Portal", "", "Portal", 10, 2),
      new Blocks(16, 17, "Lava"),
      new Blocks(18, 17, "Portal", "", "Portal", 14, 2),
      new Blocks(20, 17, "Lava"),
      new Blocks(22, 17, "Portal", "", "Portal", 18, 2),
      new Blocks(24, 17, "Lava"),
      new Blocks(29, 17, "Lava"),
      new Blocks(0, 18, "Lava"),
      new Blocks(4, 18, "Lava"),
      new Blocks(8, 18, "Lava"),
      new Blocks(12, 18, "Lava"),
      new Blocks(16, 18, "Lava"),
      new Blocks(20, 18, "Lava"),
      new Blocks(24, 18, "Lava"),
      new Blocks(29, 18, "Lava"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Lava"),
      new Blocks(8, 19, "Lava"),
      new Blocks(12, 19, "Lava"),
      new Blocks(16, 19, "Lava"),
      new Blocks(20, 19, "Lava"),
      new Blocks(24, 19, "Lava"),
      new Blocks(29, 19, "Lava"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(4, 0, "Lava"),
      new Blocks(7, 0, "Lava"),
      new Blocks(13, 0, "Lava"),
      new Blocks(19, 0, "Lava"),
      new Blocks(26, 0, "Block"),
      new Blocks(7, 1, "Lava"),
      new Blocks(10, 1, "Lava"),
      new Blocks(13, 1, "Lava"),
      new Blocks(16, 1, "Lava"),
      new Blocks(19, 1, "Lava"),
      new Blocks(22, 1, "Lava"),
      new Blocks(26, 1, "Block"),
      new Blocks(28, 1, "Portal", "", "Portal", 1, 3),
      new Blocks(4, 2, "Lava"),
      new Blocks(7, 2, "Lava"),
      new Blocks(10, 2, "Lava"),
      new Blocks(13, 2, "Lava"),
      new Blocks(16, 2, "Lava"),
      new Blocks(19, 2, "Lava"),
      new Blocks(22, 2, "Lava"),
      new Blocks(26, 2, "Block"),
      new Blocks(1, 3, "Portal", "", "Portal", 28, 1),
      new Blocks(4, 3, "Lava"),
      new Blocks(10, 3, "Lava"),
      new Blocks(16, 3, "Lava"),
      new Blocks(22, 3, "Lava"),
      new Blocks(26, 3, "Block"),
      new Blocks(0, 4, "Block"),
      new Blocks(1, 4, "Block"),
      new Blocks(2, 4, "Block"),
      new Blocks(3, 4, "Speed", "Right"),
      new Blocks(4, 4, "Speed", "Right"),
      new Blocks(5, 4, "Speed", "Right"),
      new Blocks(6, 4, "Speed", "Right"),
      new Blocks(7, 4, "Speed", "Right"),
      new Blocks(8, 4, "Speed", "Right"),
      new Blocks(9, 4, "Speed", "Right"),
      new Blocks(10, 4, "Speed", "Right"),
      new Blocks(11, 4, "Speed", "Right"),
      new Blocks(12, 4, "Speed", "Right"),
      new Blocks(13, 4, "Speed", "Right"),
      new Blocks(14, 4, "Speed", "Right"),
      new Blocks(15, 4, "Speed", "Right"),
      new Blocks(16, 4, "Speed", "Right"),
      new Blocks(17, 4, "Speed", "Right"),
      new Blocks(18, 4, "Speed", "Right"),
      new Blocks(19, 4, "Speed", "Right"),
      new Blocks(20, 4, "Speed", "Right"),
      new Blocks(21, 4, "Speed", "Right"),
      new Blocks(22, 4, "Speed", "Right"),
      new Blocks(23, 4, "Platform"),
      new Blocks(24, 4, "Platform"),
      new Blocks(25, 4, "Platform"),
      new Blocks(26, 4, "Block"),
      new Blocks(0, 5, "Lava"),
      new Blocks(1, 5, "Lava"),
      new Blocks(2, 5, "Lava"),
      new Blocks(3, 5, "Lava"),
      new Blocks(4, 5, "Lava"),
      new Blocks(5, 5, "Lava"),
      new Blocks(6, 5, "Lava"),
      new Blocks(7, 5, "Lava"),
      new Blocks(8, 5, "Lava"),
      new Blocks(9, 5, "Lava"),
      new Blocks(10, 5, "Lava"),
      new Blocks(11, 5, "Lava"),
      new Blocks(12, 5, "Lava"),
      new Blocks(13, 5, "Lava"),
      new Blocks(14, 5, "Lava"),
      new Blocks(15, 5, "Lava"),
      new Blocks(16, 5, "Lava"),
      new Blocks(17, 5, "Lava"),
      new Blocks(18, 5, "Lava"),
      new Blocks(19, 5, "Lava"),
      new Blocks(20, 5, "Lava"),
      new Blocks(21, 5, "Lava"),
      new Blocks(22, 5, "Lava"),
      new Blocks(26, 5, "Block"),
      new Blocks(26, 6, "Block"),
      new Blocks(26, 7, "Block"),
      new Blocks(26, 8, "Block"),
      new Blocks(0, 9, "Platform"),
      new Blocks(1, 9, "Platform"),
      new Blocks(2, 9, "Platform"),
      new Blocks(3, 9, "Speed", "Up"),
      new Blocks(4, 9, "Block"),
      new Blocks(5, 9, "Speed", "Up"),
      new Blocks(6, 9, "Block"),
      new Blocks(7, 9, "Speed", "Up"),
      new Blocks(8, 9, "Block"),
      new Blocks(9, 9, "Speed", "Up"),
      new Blocks(10, 9, "Block"),
      new Blocks(11, 9, "Speed", "Up"),
      new Blocks(12, 9, "Block"),
      new Blocks(13, 9, "Speed", "Up"),
      new Blocks(14, 9, "Block"),
      new Blocks(15, 9, "Speed", "Up"),
      new Blocks(16, 9, "Block"),
      new Blocks(17, 9, "Speed", "Up"),
      new Blocks(18, 9, "Block"),
      new Blocks(19, 9, "Speed", "Up"),
      new Blocks(20, 9, "Block"),
      new Blocks(21, 9, "Speed", "Up"),
      new Blocks(22, 9, "Block"),
      new Blocks(23, 9, "Block"),
      new Blocks(24, 9, "Speed", "Up"),
      new Blocks(25, 9, "Block"),
      new Blocks(26, 9, "Block"),
      new Blocks(3, 10, "Lava"),
      new Blocks(4, 10, "Lava"),
      new Blocks(5, 10, "Lava"),
      new Blocks(6, 10, "Lava"),
      new Blocks(7, 10, "Lava"),
      new Blocks(8, 10, "Lava"),
      new Blocks(9, 10, "Lava"),
      new Blocks(10, 10, "Lava"),
      new Blocks(11, 10, "Lava"),
      new Blocks(12, 10, "Lava"),
      new Blocks(13, 10, "Lava"),
      new Blocks(14, 10, "Lava"),
      new Blocks(15, 10, "Lava"),
      new Blocks(16, 10, "Lava"),
      new Blocks(17, 10, "Lava"),
      new Blocks(18, 10, "Lava"),
      new Blocks(19, 10, "Lava"),
      new Blocks(20, 10, "Lava"),
      new Blocks(21, 10, "Lava"),
      new Blocks(22, 10, "Lava"),
      new Blocks(23, 10, "Lava"),
      new Blocks(24, 10, "Lava"),
      new Blocks(25, 10, "Lava"),
      new Blocks(26, 10, "Block"),
      new Blocks(26, 11, "Block"),
      new Blocks(26, 12, "Block"),
      new Blocks(26, 13, "Block"),
      new Blocks(0, 14, "Block"),
      new Blocks(1, 14, "Speed", "Up"),
      new Blocks(2, 14, "Block"),
      new Blocks(3, 14, "Block"),
      new Blocks(4, 14, "Speed", "Up"),
      new Blocks(5, 14, "Block"),
      new Blocks(6, 14, "Block"),
      new Blocks(7, 14, "Speed", "Up"),
      new Blocks(8, 14, "Block"),
      new Blocks(9, 14, "Block"),
      new Blocks(10, 14, "Speed", "Up"),
      new Blocks(11, 14, "Block"),
      new Blocks(12, 14, "Block"),
      new Blocks(13, 14, "Speed", "Up"),
      new Blocks(14, 14, "Block"),
      new Blocks(15, 14, "Block"),
      new Blocks(16, 14, "Speed", "Up"),
      new Blocks(17, 14, "Block"),
      new Blocks(18, 14, "Block"),
      new Blocks(19, 14, "Speed", "Up"),
      new Blocks(20, 14, "Block"),
      new Blocks(21, 14, "Block"),
      new Blocks(22, 14, "Speed", "Up"),
      new Blocks(23, 14, "Platform"),
      new Blocks(24, 14, "Platform"),
      new Blocks(25, 14, "Platform"),
      new Blocks(26, 14, "Block"),
      new Blocks(0, 15, "Lava"),
      new Blocks(1, 15, "Lava"),
      new Blocks(2, 15, "Lava"),
      new Blocks(3, 15, "Lava"),
      new Blocks(4, 15, "Lava"),
      new Blocks(5, 15, "Lava"),
      new Blocks(6, 15, "Lava"),
      new Blocks(7, 15, "Lava"),
      new Blocks(8, 15, "Lava"),
      new Blocks(9, 15, "Lava"),
      new Blocks(10, 15, "Lava"),
      new Blocks(11, 15, "Lava"),
      new Blocks(12, 15, "Lava"),
      new Blocks(13, 15, "Lava"),
      new Blocks(14, 15, "Lava"),
      new Blocks(15, 15, "Lava"),
      new Blocks(16, 15, "Lava"),
      new Blocks(17, 15, "Lava"),
      new Blocks(18, 15, "Lava"),
      new Blocks(19, 15, "Lava"),
      new Blocks(20, 15, "Lava"),
      new Blocks(21, 15, "Lava"),
      new Blocks(22, 15, "Lava"),
      new Blocks(26, 15, "Block"),
      new Blocks(26, 16, "Block"),
      new Blocks(26, 17, "Block"),
      new Blocks(26, 18, "Block"),
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Speed", "Up"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Speed", "Up"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Speed", "Up"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Speed", "Up"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Speed", "Up"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Speed", "Up"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(4, 0, "Key", "", "Key"),
      new Blocks(5, 0, "Key", "", "Key"),
      new Blocks(6, 0, "LockedPortal", "", "LockedPortal", 0, 12),
      new Blocks(7, 0, "Block"),
      new Blocks(14, 0, "Block"),
      new Blocks(15, 0, "Block"),
      new Blocks(16, 0, "LockedPortal", "", "LockedPortal", 4, 18),
      new Blocks(1, 1, "Block"),
      new Blocks(2, 1, "Block"),
      new Blocks(3, 1, "Block"),
      new Blocks(4, 1, "Block"),
      new Blocks(5, 1, "Block"),
      new Blocks(6, 1, "Block"),
      new Blocks(7, 1, "Block"),
      new Blocks(14, 1, "Block"),
      new Blocks(15, 1, "Block"),
      new Blocks(16, 1, "Speed", "Left"),
      new Blocks(17, 1, "Speed", "Left"),
      new Blocks(18, 1, "Speed", "Left"),
      new Blocks(19, 1, "Speed", "Left"),
      new Blocks(20, 1, "Speed", "Left"),
      new Blocks(21, 1, "Speed", "Left"),
      new Blocks(22, 1, "Speed", "Left"),
      new Blocks(23, 1, "Speed", "Left"),
      new Blocks(24, 1, "Speed", "Left"),
      new Blocks(25, 1, "Speed", "Left"),
      new Blocks(26, 1, "Speed", "Left"),
      new Blocks(27, 1, "Speed", "Left"),
      new Blocks(28, 1, "Speed", "Left"),
      new Blocks(29, 1, "Platform"),
      new Blocks(9, 2, "Lava"),
      new Blocks(10, 2, "Lava"),
      new Blocks(11, 2, "Lava"),
      new Blocks(12, 2, "Lava"),
      new Blocks(14, 2, "Block"),
      new Blocks(15, 2, "Block"),
      new Blocks(21, 2, "Block"),
      new Blocks(25, 2, "Lava"),
      new Blocks(0, 3, "Block"),
      new Blocks(1, 3, "Block"),
      new Blocks(2, 3, "Block"),
      new Blocks(3, 3, "Block"),
      new Blocks(4, 3, "Block"),
      new Blocks(5, 3, "Block"),
      new Blocks(6, 3, "Block"),
      new Blocks(7, 3, "Block"),
      new Blocks(8, 3, "Block"),
      new Blocks(9, 3, "Lava"),
      new Blocks(10, 3, "Platform"),
      new Blocks(11, 3, "Platform"),
      new Blocks(12, 3, "Platform"),
      new Blocks(13, 3, "Platform"),
      new Blocks(14, 3, "Lava"),
      new Blocks(15, 3, "Block"),
      new Blocks(21, 3, "Block"),
      new Blocks(25, 3, "Lava"),
      new Blocks(9, 4, "Lava"),
      new Blocks(11, 4, "Speed", "Right"),
      new Blocks(12, 4, "Speed", "Right"),
      new Blocks(13, 4, "Speed", "Right"),
      new Blocks(14, 4, "Lava"),
      new Blocks(15, 4, "Block"),
      new Blocks(16, 4, "Platform"),
      new Blocks(17, 4, "Platform"),
      new Blocks(18, 4, "Platform"),
      new Blocks(19, 4, "Block"),
      new Blocks(21, 4, "Block"),
      new Blocks(25, 4, "Lava"),
      new Blocks(27, 4, "Block"),
      new Blocks(28, 4, "Block"),
      new Blocks(29, 4, "Block"),
      new Blocks(0, 5, "Platform"),
      new Blocks(1, 5, "Block"),
      new Blocks(2, 5, "Block"),
      new Blocks(3, 5, "Block"),
      new Blocks(4, 5, "Block"),
      new Blocks(5, 5, "Speed", "Right"),
      new Blocks(6, 5, "Speed", "Right"),
      new Blocks(7, 5, "Speed", "Right"),
      new Blocks(9, 5, "Lava"),
      new Blocks(14, 5, "Lava"),
      new Blocks(15, 5, "Block"),
      new Blocks(19, 5, "Block"),
      new Blocks(21, 5, "Block"),
      new Blocks(22, 5, "Platform"),
      new Blocks(23, 5, "Block"),
      new Blocks(24, 5, "Red"),
      new Blocks(25, 5, "Lava"),
      new Blocks(7, 6, "Block"),
      new Blocks(9, 6, "Lava"),
      new Blocks(10, 6, "Speed", "Left"),
      new Blocks(11, 6, "Speed", "Left"),
      new Blocks(12, 6, "Speed", "Left"),
      new Blocks(14, 6, "Lava"),
      new Blocks(15, 6, "Block"),
      new Blocks(19, 6, "Block"),
      new Blocks(21, 6, "Block"),
      new Blocks(23, 6, "Block"),
      new Blocks(25, 6, "Lava"),
      new Blocks(26, 6, "Speed", "Right"),
      new Blocks(27, 6, "Speed", "Right"),
      new Blocks(28, 6, "Speed", "Right"),
      new Blocks(7, 7, "Block"),
      new Blocks(14, 7, "Lava"),
      new Blocks(15, 7, "Block"),
      new Blocks(16, 7, "Platform"),
      new Blocks(17, 7, "Platform"),
      new Blocks(18, 7, "Platform"),
      new Blocks(19, 7, "Block"),
      new Blocks(21, 7, "Lava"),
      new Blocks(23, 7, "Block"),
      new Blocks(7, 8, "Block"),
      new Blocks(8, 8, "Block"),
      new Blocks(9, 8, "Block"),
      new Blocks(10, 8, "Block"),
      new Blocks(11, 8, "Speed", "Right"),
      new Blocks(12, 8, "Speed", "Right"),
      new Blocks(13, 8, "Speed", "Right"),
      new Blocks(14, 8, "Block"),
      new Blocks(15, 8, "Block"),
      new Blocks(19, 8, "Block"),
      new Blocks(23, 8, "Block"),
      new Blocks(24, 8, "Blue"),
      new Blocks(25, 8, "Blue"),
      new Blocks(26, 8, "Blue"),
      new Blocks(27, 8, "Blue"),
      new Blocks(28, 8, "Blue"),
      new Blocks(29, 8, "Blue"),
      new Blocks(8, 9, "Lava"),
      new Blocks(14, 9, "Block"),
      new Blocks(15, 9, "Block"),
      new Blocks(19, 9, "Block"),
      new Blocks(23, 9, "Block"),
      new Blocks(0, 10, "Speed", "Up"),
      new Blocks(1, 10, "Lava"),
      new Blocks(2, 10, "Lava"),
      new Blocks(3, 10, "Lava"),
      new Blocks(4, 10, "Lava"),
      new Blocks(5, 10, "Lava"),
      new Blocks(6, 10, "Block"),
      new Blocks(8, 10, "Lava"),
      new Blocks(14, 10, "Block"),
      new Blocks(15, 10, "Block"),
      new Blocks(16, 10, "Platform"),
      new Blocks(17, 10, "Platform"),
      new Blocks(18, 10, "Platform"),
      new Blocks(19, 10, "Block"),
      new Blocks(23, 10, "Block"),
      new Blocks(0, 11, "Block"),
      new Blocks(1, 11, "Block"),
      new Blocks(2, 11, "Block"),
      new Blocks(3, 11, "Block"),
      new Blocks(4, 11, "Block"),
      new Blocks(5, 11, "Block"),
      new Blocks(6, 11, "Block"),
      new Blocks(8, 11, "Lava"),
      new Blocks(10, 11, "Lava"),
      new Blocks(14, 11, "Block"),
      new Blocks(15, 11, "Block"),
      new Blocks(19, 11, "Block"),
      new Blocks(23, 11, "Block"),
      new Blocks(0, 12, "LockedPortal", "", "LockedPortal", 6, 0),
      new Blocks(10, 12, "Lava"),
      new Blocks(14, 12, "Block"),
      new Blocks(15, 12, "Block"),
      new Blocks(19, 12, "Block"),
      new Blocks(20, 12, "Speed", "Up"),
      new Blocks(21, 12, "Speed", "Up"),
      new Blocks(22, 12, "Speed", "Up"),
      new Blocks(23, 12, "Block"),
      new Blocks(24, 12, "Lava"),
      new Blocks(25, 12, "Lava"),
      new Blocks(26, 12, "Lava"),
      new Blocks(27, 12, "Lava"),
      new Blocks(28, 12, "Lava"),
      new Blocks(29, 12, "Lava"),
      new Blocks(0, 13, "Block"),
      new Blocks(1, 13, "Block"),
      new Blocks(2, 13, "Block"),
      new Blocks(3, 13, "Block"),
      new Blocks(4, 13, "Block"),
      new Blocks(5, 13, "Block"),
      new Blocks(6, 13, "Block"),
      new Blocks(7, 13, "Block"),
      new Blocks(8, 13, "Block"),
      new Blocks(9, 13, "Block"),
      new Blocks(10, 13, "Block"),
      new Blocks(11, 13, "Red"),
      new Blocks(12, 13, "Red"),
      new Blocks(13, 13, "Red"),
      new Blocks(14, 13, "Block"),
      new Blocks(15, 13, "Block"),
      new Blocks(16, 13, "Blue"),
      new Blocks(17, 13, "Blue"),
      new Blocks(18, 13, "Blue"),
      new Blocks(19, 13, "Block"),
      new Blocks(20, 13, "Block"),
      new Blocks(21, 13, "Block"),
      new Blocks(22, 13, "Block"),
      new Blocks(23, 13, "Block"),
      new Blocks(24, 13, "Block"),
      new Blocks(25, 13, "Block"),
      new Blocks(26, 13, "Block"),
      new Blocks(27, 13, "Block"),
      new Blocks(28, 13, "Block"),
      new Blocks(29, 13, "Block"),
      new Blocks(0, 16, "Platform"),
      new Blocks(1, 16, "Platform"),
      new Blocks(2, 16, "Platform"),
      new Blocks(3, 16, "Block"),
      new Blocks(4, 16, "Platform"),
      new Blocks(5, 16, "Platform"),
      new Blocks(6, 16, "Platform"),
      new Blocks(7, 16, "Platform"),
      new Blocks(8, 16, "Platform"),
      new Blocks(9, 16, "Platform"),
      new Blocks(10, 16, "Platform"),
      new Blocks(11, 16, "Platform"),
      new Blocks(12, 16, "Platform"),
      new Blocks(13, 16, "Platform"),
      new Blocks(14, 16, "Platform"),
      new Blocks(15, 16, "Platform"),
      new Blocks(16, 16, "Platform"),
      new Blocks(17, 16, "Platform"),
      new Blocks(18, 16, "Platform"),
      new Blocks(19, 16, "Platform"),
      new Blocks(20, 16, "Platform"),
      new Blocks(21, 16, "Platform"),
      new Blocks(22, 16, "Platform"),
      new Blocks(23, 16, "Platform"),
      new Blocks(24, 16, "Platform"),
      new Blocks(25, 16, "Platform"),
      new Blocks(26, 16, "Platform"),
      new Blocks(27, 16, "Platform"),
      new Blocks(28, 16, "Platform"),
      new Blocks(29, 16, "Platform"),
      new Blocks(3, 17, "Block"),
      new Blocks(3, 18, "Block"),
      new Blocks(4, 18, "LockedPortal", "", "LockedPortal", 16, 0),
      new Blocks(1, 19, "Speed", "Up"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Speed", "Right"),
      new Blocks(7, 19, "Speed", "Right"),
      new Blocks(8, 19, "Speed", "Right"),
      new Blocks(9, 19, "Speed", "Right"),
      new Blocks(10, 19, "Speed", "Right"),
      new Blocks(11, 19, "Speed", "Right"),
      new Blocks(12, 19, "Speed", "Right"),
      new Blocks(13, 19, "Speed", "Right"),
      new Blocks(14, 19, "Speed", "Right"),
      new Blocks(15, 19, "Speed", "Right"),
      new Blocks(16, 19, "Speed", "Right"),
      new Blocks(17, 19, "Speed", "Right"),
      new Blocks(18, 19, "Speed", "Right"),
      new Blocks(19, 19, "Speed", "Right"),
      new Blocks(20, 19, "Speed", "Right"),
      new Blocks(21, 19, "Speed", "Right"),
      new Blocks(22, 19, "Speed", "Right"),
      new Blocks(23, 19, "Speed", "Right"),
      new Blocks(24, 19, "Speed", "Right"),
      new Blocks(25, 19, "Speed", "Right"),
      new Blocks(26, 19, "Speed", "Right"),
      new Blocks(27, 19, "Speed", "Right"),
      new Blocks(28, 18, "Flag"),
    ]);
    Levels.push([
      new Blocks(0, 19, "Block"),
      new Blocks(1, 19, "Block"),
      new Blocks(2, 19, "Block"),
      new Blocks(3, 19, "Block"),
      new Blocks(4, 19, "Block"),
      new Blocks(5, 19, "Block"),
      new Blocks(6, 19, "Block"),
      new Blocks(7, 19, "Block"),
      new Blocks(8, 19, "Block"),
      new Blocks(9, 19, "Block"),
      new Blocks(10, 19, "Block"),
      new Blocks(11, 19, "Block"),
      new Blocks(12, 19, "Block"),
      new Blocks(13, 19, "Block"),
      new Blocks(14, 19, "Block"),
      new Blocks(15, 19, "Block"),
      new Blocks(16, 19, "Block"),
      new Blocks(17, 19, "Block"),
      new Blocks(18, 19, "Block"),
      new Blocks(19, 19, "Block"),
      new Blocks(20, 19, "Block"),
      new Blocks(21, 19, "Block"),
      new Blocks(22, 19, "Block"),
      new Blocks(23, 19, "Block"),
      new Blocks(24, 19, "Block"),
      new Blocks(25, 19, "Block"),
      new Blocks(26, 19, "Block"),
      new Blocks(27, 19, "Block"),
      new Blocks(28, 19, "Block"),
      new Blocks(29, 19, "Block"),
    ]);
  }
};
